// <auto-generated>

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using System;

namespace TestNamespace;

[Register("AVAudioPCMBuffer", true)]
public unsafe partial class AVAudioPcmBuffer
{
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static readonly NativeHandle class_ptr = Class.GetHandle ("AVAudioPCMBuffer");

	/// <summary>The Objective-C class handle for this class.</summary>
	/// <value>The pointer to the Objective-C class.</value>
	/// <remarks>
	///     Each managed class mirrors an unmanaged Objective-C class.
	///     This value contains the pointer to the Objective-C class.
	///     It is similar to calling the managed <see cref="ObjCRuntime.Class.GetHandle(string)" /> or the native <see href="https://developer.apple.com/documentation/objectivec/1418952-objc_getclass">objc_getClass</see> method with the type name.
	/// </remarks>
	public override NativeHandle ClassHandle { get { return class_ptr; } }

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial NativeHandle InitWithPCMFormatFrameCapacity (AVAudioFormat format, uint /* AVAudioFrameCount = uint32_t */ frameCapacity)
	{
		// TODO: add constructor binding code here for AVAudioPcmBuffer
		return default;
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial NativeHandle InitWithPCMFormatBufferListNoCopy (AVAudioFormat format, AudioBuffers bufferList, Action<AudioBuffers>? deallocator)
	{
		// TODO: add constructor binding code here for AVAudioPcmBuffer
		return default;
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial void FinishedPlaying (AVAudioPlayer player, bool flag)
	{
		// TODO: add property binding code here for AVAudioPcmBuffer
		return;
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial void DecoderError (AVAudioPlayer player, NSError? error)
	{
		// TODO: add property binding code here for AVAudioPcmBuffer
		return;
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial uint FrameCapacity
	{
		get
		{
			// TODO: add code for AVAudioPcmBuffer
			return default;
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial uint FrameLength
	{
		get
		{
			// TODO: add code for AVAudioPcmBuffer
			return default;
		}
		set
		{
			// TODO: add code for AVAudioPcmBuffer
			return;
		}
	}

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual partial nuint Stride
	{
		get
		{
			// TODO: add code for AVAudioPcmBuffer
			return default;
		}
	}

}
