id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - weekday:
          day: Monday
          time: 0:0
      - weekday:
          day: Tuesday
          time: 0:0
      - weekday:
          day: Wednesday
          time: 0:0
      - weekday:
          day: Thursday
          time: 0:0
      - weekday:
          day: Friday
          time: 0:0
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: need-info
      - noActivitySince:
          days: 7
      actions:
      - addReply:
          reply: Hi @${issueAuthor}. Due to inactivity, we will be closing this issue. Please feel free to re-open this issue if the issue persists. For enhanced visibility, if over 7 days have passed, please open a new issue and link this issue there. Thank you.
      - closeIssue
    - description: 
      frequencies:
      - weekday:
          day: Monday
          time: 0:0
      - weekday:
          day: Tuesday
          time: 0:0
      - weekday:
          day: Wednesday
          time: 0:0
      - weekday:
          day: Thursday
          time: 0:0
      - weekday:
          day: Friday
          time: 0:0
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: need-repro
      - noActivitySince:
          days: 7
      actions:
      - addReply:
          reply: Hi @${issueAuthor}. Due to inactivity, we will be closing this issue. Please feel free to re-open this issue if the issue persists. For enhanced visibility, if over 7 days have passed, please open a new issue and link this issue there. Thank you.
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isOpen
      - hasLabel:
          label: move-to-vs-feedback
      - noActivitySince:
          days: 3
      actions:
      - addReply:
          reply: This issue is being closed due to inactivity. If this issue is still affecting you, please follow the steps above to use the VS Feedback Tool to report the issue.
      - closeIssue

    - description: Add comment letting user know their PR is out of date.
      frequencies:
      - weekday:
          day: Monday
          time: 0:0
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: community
      - noActivitySince:
          days: 21
      actions:
      - addReply:
          reply: Hi @{issueAuthor}. Due to inactivity, we will close this pull request in 7 days.

    - description: Closing out-of-date community PRs.
      frequencies:
      - weekday:
          day: Monday
          time: 0:0
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: community
      - noActivitySince:
          days: 28
      actions:
      - addReply:
          reply: Hi @{issueAuthor}. This pull request was closed due to inactivity. Please let us know if you'd like to reopen it.
      - closePullRequest

    eventResponderTasks:

    - if:
      - payloadType: Issues
      - labelAdded:
          label: need-info
      then:
      - if:
        - not:
            hasLabel: no-auto-reply
        then:
        - addReply:
            reply: Hi @${issueAuthor}. We have added the "need-info" label to this issue, which indicates that we have an open question for you before we can take further action. This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.
      - if:
        - hasLabel: no-auto-reply
        then:
        - removeLabel:
            label: no-auto-reply
      description: "Add comment asking for info when the 'need-info' label is added to an issue."

    - if:
      - payloadType: Issues
      - labelAdded:
          label: need-repro
      then:
      - if:
        - not:
            hasLabel: no-auto-reply
        then:
        - addReply:
            reply: >-
              Hi @${issueAuthor}. We have added the "need-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/xamarin/xamarin-macios/blob/main/docs/bug-repro.md

              This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.
      - if:
        - hasLabel: no-auto-reply
        then:
        - removeLabel:
            label: no-auto-reply
      description: "Add comment asking for info when the 'need-repro' label is added to an issue."

    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isOpen
      - or:
        - hasLabel:
            label: need-info
        - hasLabel:
            label: need-repro
      - not:
          activitySenderHasPermission:
            permission: Admin
      - not:
          activitySenderHasPermission:
            permission: Write
      - not:
          isActivitySender:
            user: msftbot
      then:
      - removeLabel:
          label: need-info
      - removeLabel:
          label: need-repro
      - addLabel:
          label: need-attention
      description: 
    - if:
      - payloadType: Issues
      - isOpen
      - labelAdded:
          label: move-to-vs-feedback
      then:
      - addReply:
          reply: >-
            Thanks for the issue report @${issueAuthor}! This issue appears to be a problem with Visual Studio, so we ask that you use the VS feedback tool to report the issue. That way it will get to the routed to the team that owns this experience in VS.


            If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks.


            1. Go to the [Visual Studio for Windows feedback tool](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) or [Visual Studio for Mac feedback tool](https://learn.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2022) to report the issue

            2. Close this bug, and consider adding a link to the VS Feedback issue so that others can follow its activity there.


            This issue will be automatically closed in 3 days if there are no further comments.
      description: 
onFailure: 
onSuccess: 
