//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bgen {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bgen.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error message for code {0} could not be found. Please report this missing message on GitHub at https://github.com/xamarin/xamarin-macios/issues/new.
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error - Please fill a bug report at https://github.com/xamarin/xamarin-macios/issues/new.
        /// </summary>
        internal static string BI0000 {
            get {
                return ResourceManager.GetString("BI0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET runtime could not load the {0} type. Message: {1}.
        /// </summary>
        internal static string BI0001 {
            get {
                return ResourceManager.GetString("BI0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not compile the API bindings.
        ///		{0}
        ///		.
        /// </summary>
        internal static string BI0002 {
            get {
                return ResourceManager.GetString("BI0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frameworks were not loaded for platform {0}..
        /// </summary>
        internal static string BI0003 {
            get {
                return ResourceManager.GetString("BI0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universe was not loaded for platform {0}..
        /// </summary>
        internal static string BI0004 {
            get {
                return ResourceManager.GetString("BI0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the command line argument &apos;--warnaserror&apos;: {0}.
        /// </summary>
        internal static string BI0026 {
            get {
                return ResourceManager.GetString("BI0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse the command line argument &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string BI0027 {
            get {
                return ResourceManager.GetString("BI0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No C# compiler has been specified (using --compiler or --compile-command)..
        /// </summary>
        internal static string BI0028 {
            get {
                return ResourceManager.GetString("BI0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for target framework: {0}..
        /// </summary>
        internal static string BI0068 {
            get {
                return ResourceManager.GetString("BI0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target framework: {0}. Valid target frameworks are: {1}..
        /// </summary>
        internal static string BI0070 {
            get {
                return ResourceManager.GetString("BI0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A target framework (--target-framework) must be specified..
        /// </summary>
        internal static string BI0086 {
            get {
                return ResourceManager.GetString("BI0086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xamarin.Mac Classic binding projects are not supported anymore. Please upgrade the binding project to a Xamarin.Mac Unified binding project..
        /// </summary>
        internal static string BI0087 {
            get {
                return ResourceManager.GetString("BI0087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: don&apos;t know how to create ref/out (input) code for {0} in {1}. Please file a bug report with a test case (https://github.com/xamarin/xamarin-macios/issues/new)..
        /// </summary>
        internal static string BI0088 {
            get {
                return ResourceManager.GetString("BI0088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: property {0} doesn&apos;t have neither a getter nor a setter..
        /// </summary>
        internal static string BI0089 {
            get {
                return ResourceManager.GetString("BI0089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error {0}. Please file a bug report with a test case (https://github.com/xamarin/xamarin-macios/issues/new)..
        /// </summary>
        internal static string BI0099 {
            get {
                return ResourceManager.GetString("BI0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not compile the generated API bindings.	
        ///		{0}
        ///		.
        /// </summary>
        internal static string BI1000 {
            get {
                return ResourceManager.GetString("BI1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not know how to make a trampoline for {0}.
        /// </summary>
        internal static string BI1001 {
            get {
                return ResourceManager.GetString("BI1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown kind {0} in method &apos;{1}.{2}&apos;.
        /// </summary>
        internal static string BI1002 {
            get {
                return ResourceManager.GetString("BI1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delegate method {0}.{1} needs to take at least one parameter.
        /// </summary>
        internal static string BI1003 {
            get {
                return ResourceManager.GetString("BI1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delegate method {0}.{1} is missing the [EventArgs] attribute (has {2} parameters).
        /// </summary>
        internal static string BI1004 {
            get {
                return ResourceManager.GetString("BI1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventArgs in {0}.{1} attribute should not include the text `EventArgs&apos; at the end.
        /// </summary>
        internal static string BI1005 {
            get {
                return ResourceManager.GetString("BI1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delegate method {0}.{1} is missing the [DelegateName] attribute (or EventArgs).
        /// </summary>
        internal static string BI1006 {
            get {
                return ResourceManager.GetString("BI1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown attribute {0} on {1}.{2}.
        /// </summary>
        internal static string BI1007 {
            get {
                return ResourceManager.GetString("BI1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [IsThreadStatic] is only valid on properties that are also [Static].
        /// </summary>
        internal static string BI1008 {
            get {
                return ResourceManager.GetString("BI1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selector specified for method `{0}.{1}&apos;.
        /// </summary>
        internal static string BI1009 {
            get {
                return ResourceManager.GetString("BI1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Export attribute on {0}.{1} property.
        /// </summary>
        internal static string BI1010 {
            get {
                return ResourceManager.GetString("BI1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not know how to extract type {0}/{1} from an NSDictionary.
        /// </summary>
        internal static string BI1011 {
            get {
                return ResourceManager.GetString("BI1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Export or Bind attribute defined on {0}.{1}.
        /// </summary>
        internal static string BI1012 {
            get {
                return ResourceManager.GetString("BI1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type for Fields (string), you probably meant NSString.
        /// </summary>
        internal static string BI1013 {
            get {
                return ResourceManager.GetString("BI1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type for Fields: {0} for &apos;{1}&apos;..
        /// </summary>
        internal static string BI1014 {
            get {
                return ResourceManager.GetString("BI1014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In class {0} You specified the Events property, but did not bind those to names with Delegates.
        /// </summary>
        internal static string BI1015 {
            get {
                return ResourceManager.GetString("BI1015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delegate method {0}.{1} is missing the [DefaultValue] attribute.
        /// </summary>
        internal static string BI1016 {
            get {
                return ResourceManager.GetString("BI1016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not know how to make a signature for {0}.
        /// </summary>
        internal static string BI1017 {
            get {
                return ResourceManager.GetString("BI1017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No [Export] attribute on property {0}.{1}.
        /// </summary>
        internal static string BI1018 {
            get {
                return ResourceManager.GetString("BI1018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid [NoDefaultValue] attribute on method &apos;{0}.{1}&apos;.
        /// </summary>
        internal static string BI1019 {
            get {
                return ResourceManager.GetString("BI1019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type {0} used on exported method {1}.{2} -&gt; {3}.
        /// </summary>
        internal static string BI1020 {
            get {
                return ResourceManager.GetString("BI1020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type for read/write Fields: {0} for {1}.{2}.
        /// </summary>
        internal static string BI1021 {
            get {
                return ResourceManager.GetString("BI1021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model classes can not be categories.
        /// </summary>
        internal static string BI1022 {
            get {
                return ResourceManager.GetString("BI1022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of Events (Type) and Delegates (string) must match for `{0}`.
        /// </summary>
        internal static string BI1023 {
            get {
                return ResourceManager.GetString("BI1023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selector specified for property &apos;{0}.{1}&apos;.
        /// </summary>
        internal static string BI1024 {
            get {
                return ResourceManager.GetString("BI1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Static] and [Protocol] are mutually exclusive ({0}).
        /// </summary>
        internal static string BI1025 {
            get {
                return ResourceManager.GetString("BI1025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `{0}`: Enums attributed with [{1}] must have an underlying type of `long` or `ulong`.
        /// </summary>
        internal static string BI1026 {
            get {
                return ResourceManager.GetString("BI1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support for ZeroCopy strings is not implemented. Strings will be marshalled as NSStrings..
        /// </summary>
        internal static string BI1027 {
            get {
                return ResourceManager.GetString("BI1027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal sanity check failed, please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1028 {
            get {
                return ResourceManager.GetString("BI1028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: invalid enum mode for type &apos;{0}&apos;.
        /// </summary>
        internal static string BI1029 {
            get {
                return ResourceManager.GetString("BI1029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot have [BaseType(typeof({1}))] as it creates a circular dependency.
        /// </summary>
        internal static string BI1030 {
            get {
                return ResourceManager.GetString("BI1030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Target] attribute is not supported for the Unified API (found on the member &apos;{0}.{1}&apos;). For Objective-C categories, create an api definition interface with the [Category] attribute instead..
        /// </summary>
        internal static string BI1031 {
            get {
                return ResourceManager.GetString("BI1031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No support for setters in StrongDictionary classes for type {0} in {1}.{2}.
        /// </summary>
        internal static string BI1032 {
            get {
                return ResourceManager.GetString("BI1032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation: can not automatically create strongly typed dictionary for ({0}) the value type of the {1}.{2} property.
        /// </summary>
        internal static string BI1033 {
            get {
                return ResourceManager.GetString("BI1033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Protocolize] attribute is set on the member {0}.{1}, but the member&apos;s type ({2}) is not a protocol..
        /// </summary>
        internal static string BI1034 {
            get {
                return ResourceManager.GetString("BI1034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0} on class {1} is hiding a property from a parent class {2} but the selectors do not match..
        /// </summary>
        internal static string BI1035 {
            get {
                return ResourceManager.GetString("BI1035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last parameter in the method &apos;{0}.{1}&apos; must be a delegate (it&apos;s &apos;{2}&apos;)..
        /// </summary>
        internal static string BI1036 {
            get {
                return ResourceManager.GetString("BI1036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector {0} on type {1} is found multiple times with both read only and write only versions, with no read/write version..
        /// </summary>
        internal static string BI1037 {
            get {
                return ResourceManager.GetString("BI1037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector {0} on type {1} is found multiple times with different return types..
        /// </summary>
        internal static string BI1038 {
            get {
                return ResourceManager.GetString("BI1038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector {0} on type {1} is found multiple times with different argument length {2} : {3}..
        /// </summary>
        internal static string BI1039 {
            get {
                return ResourceManager.GetString("BI1039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector {0} on type {1} is found multiple times with different argument out states on argument {2}..
        /// </summary>
        internal static string BI1040 {
            get {
                return ResourceManager.GetString("BI1040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selector {0} on type {1} is found multiple times with different argument types on argument {2} - {3} : {4}.		.
        /// </summary>
        internal static string BI1041 {
            get {
                return ResourceManager.GetString("BI1041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;[Field (LibraryName=value)]&apos; for {0} (e.g.&quot;__Internal&quot;).
        /// </summary>
        internal static string BI1042 {
            get {
                return ResourceManager.GetString("BI1042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated overload {0} and no [DelegateApiNameAttribute] provided to generate property name on host class..
        /// </summary>
        internal static string BI1043 {
            get {
                return ResourceManager.GetString("BI1043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeated name &apos;{0}&apos; provided in [DelegateApiNameAttribute]..
        /// </summary>
        internal static string BI1044 {
            get {
                return ResourceManager.GetString("BI1044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a single [DefaultEnumValue] attribute can be used inside enum {0}..
        /// </summary>
        internal static string BI1045 {
            get {
                return ResourceManager.GetString("BI1045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Field] constant {0} cannot only be used once inside enum {1}..
        /// </summary>
        internal static string BI1046 {
            get {
                return ResourceManager.GetString("BI1046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported platform: {0}. Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1047 {
            get {
                return ResourceManager.GetString("BI1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type {0} decorated with [BindAs].
        /// </summary>
        internal static string BI1048 {
            get {
                return ResourceManager.GetString("BI1048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not {0} type {1} from {2} {3} used on member {4} decorated with [BindAs]..
        /// </summary>
        internal static string BI1049 {
            get {
                return ResourceManager.GetString("BI1049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BindAs] cannot be used inside Protocol or Model types. Type: {0}.
        /// </summary>
        internal static string BI1050 {
            get {
                return ResourceManager.GetString("BI1050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Don&apos;t know how to get attributes for {0}. Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1051 {
            get {
                return ResourceManager.GetString("BI1051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: Could not find the type {0} in the assembly {1}. Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1052 {
            get {
                return ResourceManager.GetString("BI1052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: unknown target framework &apos;{0}&apos;..
        /// </summary>
        internal static string BI1053 {
            get {
                return ResourceManager.GetString("BI1053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: can&apos;t convert type &apos;{0}&apos; (unknown assembly). Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1054 {
            get {
                return ResourceManager.GetString("BI1054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: failed to convert type &apos;{0}&apos;. Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1055 {
            get {
                return ResourceManager.GetString("BI1055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: failed to instantiate mock attribute &apos;{0}&apos; (could not convert type constructor argument #{1}). Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1056 {
            get {
                return ResourceManager.GetString("BI1056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: failed to instantiate mock attribute &apos;{0}&apos; (could not convert constructor type #{1} ({2})). Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1057 {
            get {
                return ResourceManager.GetString("BI1057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: could not find a constructor for the mock attribute &apos;{0}&apos;. Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1058 {
            get {
                return ResourceManager.GetString("BI1058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} {1} attributes on the member {2}. At most one was expected..
        /// </summary>
        internal static string BI1059 {
            get {
                return ResourceManager.GetString("BI1059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} protocol is decorated with [Model], but not [BaseType]. Please verify that [Model] is relevant for this protocol; if so, add [BaseType] as well, otherwise remove [Model]..
        /// </summary>
        internal static string BI1060 {
            get {
                return ResourceManager.GetString("BI1060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; found on &apos;{1}&apos; is not a valid binding attribute. Please remove this attribute..
        /// </summary>
        internal static string BI1061 {
            get {
                return ResourceManager.GetString("BI1061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}.{1}&apos; contains ref/out parameters and must not be decorated with [Async]..
        /// </summary>
        internal static string BI1062 {
            get {
                return ResourceManager.GetString("BI1062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;WrapAttribute&apos; can only be used at the property or at getter/setter level at a given time. Property: &apos;{0}.{1}&apos;.
        /// </summary>
        internal static string BI1063 {
            get {
                return ResourceManager.GetString("BI1063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported ref/out parameter type &apos;{0}&apos; for the parameter &apos;{1}&apos; in {2}.{3}..
        /// </summary>
        internal static string BI1064 {
            get {
                return ResourceManager.GetString("BI1064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported parameter type &apos;{0}&apos; for the parameter &apos;{1}&apos; in {2}.{3}..
        /// </summary>
        internal static string BI1065 {
            get {
                return ResourceManager.GetString("BI1065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported return type &apos;{0}&apos; in {1}.{2}..
        /// </summary>
        internal static string BI1066 {
            get {
                return ResourceManager.GetString("BI1066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is trying to inline the property &apos;{1}&apos; from the protocols &apos;{2}&apos; and &apos;{3}&apos;, but the inlined properties don&apos;t share the same accessors (&apos;{4}&apos; is read-only, while &apos;${5}&apos; is write-only)..
        /// </summary>
        internal static string BI1067 {
            get {
                return ResourceManager.GetString("BI1067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is trying to inline the property &apos;{1}&apos; from the protocols &apos;{2}&apos; and &apos;{3}&apos;, and the inlined properties use different selectors ({4}.{5} uses &apos;{6}&apos;, and {7}.{8} uses &apos;{9}&apos;..
        /// </summary>
        internal static string BI1068 {
            get {
                return ResourceManager.GetString("BI1068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is trying to inline the methods binding the selector &apos;{1}&apos; from the protocols &apos;{2}&apos; and &apos;{3}&apos;, using methods with different signatures (&apos;{4}&apos; vs &apos;{5}&apos;)..
        /// </summary>
        internal static string BI1069 {
            get {
                return ResourceManager.GetString("BI1069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is trying to inline the property &apos;{1}&apos; from the protocols &apos;{2}&apos; and &apos;{3}&apos;, but the inlined properties are of different types (&apos;{4}&apos; is {5}, while &apos;{6}&apos; is {7})..
        /// </summary>
        internal static string BI1070 {
            get {
                return ResourceManager.GetString("BI1070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BindAs type for the member &quot;{0}.{1}&quot; must be an array when the member&apos;s type is an array..
        /// </summary>
        internal static string BI1071 {
            get {
                return ResourceManager.GetString("BI1071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BindAs type for the parameter &quot;{0}&quot; in the method &quot;{1}.{2}&quot; must be an array when the parameter&apos;s type is an array..
        /// </summary>
        internal static string BI1072 {
            get {
                return ResourceManager.GetString("BI1072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: failed to instantiate mock attribute &apos;{0}&apos; (unknown type for the named argument #{1} ({2}). Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1073 {
            get {
                return ResourceManager.GetString("BI1073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Missing [CoreImageFilterProperty] attribute on {0} property {1}.
        /// </summary>
        internal static string BI1074 {
            get {
                return ResourceManager.GetString("BI1074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unimplemented CoreImage property type {0}.
        /// </summary>
        internal static string BI1075 {
            get {
                return ResourceManager.GetString("BI1075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find selector for {0} on {1} on self or base class.
        /// </summary>
        internal static string BI1076 {
            get {
                return ResourceManager.GetString("BI1076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async method {0} with more than one result parameter in the callback by neither ResultTypeName or ResultType.
        /// </summary>
        internal static string BI1077 {
            get {
                return ResourceManager.GetString("BI1077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in method `{1}&apos;.
        /// </summary>
        internal static string BI1078 {
            get {
                return ResourceManager.GetString("BI1078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in parameter `{1}&apos; from {2}.{3}.
        /// </summary>
        internal static string BI1079 {
            get {
                return ResourceManager.GetString("BI1079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported type &apos;ref/out {0}&apos; decorated with [BindAs].
        /// </summary>
        internal static string BI1080 {
            get {
                return ResourceManager.GetString("BI1080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the assembly &apos;{0}&apos;. Add it as a reference using its full path..
        /// </summary>
        internal static string BI1081 {
            get {
                return ResourceManager.GetString("BI1081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector name missing in [CoreImageFilterProperty] attribute on {0} property {1}.
        /// </summary>
        internal static string BI1082 {
            get {
                return ResourceManager.GetString("BI1082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to use a string as a [Target].
        /// </summary>
        internal static string BI1101 {
            get {
                return ResourceManager.GetString("BI1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using the deprecated &apos;EventArgs&apos; for a delegate signature in {0}.{1}, please use &apos;DelegateName&apos; instead..
        /// </summary>
        internal static string BI1102 {
            get {
                return ResourceManager.GetString("BI1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not live under a namespace; namespaces are a highly recommended .NET best practice.
        /// </summary>
        internal static string BI1103 {
            get {
                return ResourceManager.GetString("BI1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the referenced library &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string BI1104 {
            get {
                return ResourceManager.GetString("BI1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential selector/argument mismatch [Export (&quot;{0}&quot;)] has {1} arguments and {2} has {3} arguments.
        /// </summary>
        internal static string BI1105 {
            get {
                return ResourceManager.GetString("BI1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {2} in the method {0}.{1} exposes a model ({3}). Please expose the corresponding protocol type instead ({4}.I{5})..
        /// </summary>
        internal static string BI1106 {
            get {
                return ResourceManager.GetString("BI1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return type of the method {0}.{1} exposes a model ({2}). Please expose the corresponding protocol type instead ({3}.I{4})..
        /// </summary>
        internal static string BI1107 {
            get {
                return ResourceManager.GetString("BI1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The [Protocolize] attribute is applied to the return type of the method {0}.{1}, but the return type ({2}) isn&apos;t a model and can thus not be protocolized. Please remove the [Protocolize] attribute..
        /// </summary>
        internal static string BI1108 {
            get {
                return ResourceManager.GetString("BI1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return type of the method {0}.{1} exposes a model ({2}). Please expose the corresponding protocol type instead ({3}.I{4})..
        /// </summary>
        internal static string BI1109 {
            get {
                return ResourceManager.GetString("BI1109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} exposes a model ({2}). Please expose the corresponding protocol type instead ({3}.I{4})..
        /// </summary>
        internal static string BI1110 {
            get {
                return ResourceManager.GetString("BI1110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface &apos;{0}&apos; on &apos;{1}&apos; is being ignored as it is not a protocol. Did you mean &apos;{2}&apos; instead?.
        /// </summary>
        internal static string BI1111 {
            get {
                return ResourceManager.GetString("BI1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} should be renamed to &apos;Delegate&apos; for BaseType.Events and BaseType.Delegates to work..
        /// </summary>
        internal static string BI1112 {
            get {
                return ResourceManager.GetString("BI1112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseType.Delegates were set but no properties could be found. Do ensure that the WrapAttribute is used on the right properties..
        /// </summary>
        internal static string BI1113 {
            get {
                return ResourceManager.GetString("BI1113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding error: test unable to find property: {0} on {1}.
        /// </summary>
        internal static string BI1114 {
            get {
                return ResourceManager.GetString("BI1114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; in the delegate &apos;{1}&apos; does not have a [CCallback] or [BlockCallback] attribute. Defaulting to [CCallback]..
        /// </summary>
        internal static string BI1115 {
            get {
                return ResourceManager.GetString("BI1115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; in the delegate &apos;{1}&apos; does not have a [CCallback] or [BlockCallback] attribute. Defaulting to [CCallback]. Declare a custom delegate instead of using System.Action / System.Func and add the attribute on the corresponding parameter..
        /// </summary>
        internal static string BI1116 {
            get {
                return ResourceManager.GetString("BI1116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member &apos;{0}&apos; is decorated with [Static] and its container class {1} is decorated with [Category] this leads to hard to use code. Please inline {0} into {2} class..
        /// </summary>
        internal static string BI1117 {
            get {
                return ResourceManager.GetString("BI1117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NullAllowed] should not be used on methods, like &apos;{0}&apos;, but only on properties, parameters and return values..
        /// </summary>
        internal static string BI1118 {
            get {
                return ResourceManager.GetString("BI1118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: found the same type ({0}) in multiple assemblies ({1} and {2}). Please file a bug report (https://github.com/xamarin/xamarin-macios/issues/new) with a test case..
        /// </summary>
        internal static string BI1119 {
            get {
                return ResourceManager.GetString("BI1119", resourceCulture);
            }
        }
    }
}
