//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Macios.Bindings.Analyzer {

    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Microsoft.Macios.Bindings.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RBI0001Description {
            get {
                return ResourceManager.GetString("RBI0001Description", resourceCulture);
            }
        }
        
        internal static string RBI0001MessageFormat {
            get {
                return ResourceManager.GetString("RBI0001MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0001Title {
            get {
                return ResourceManager.GetString("RBI0001Title", resourceCulture);
            }
        }
        
        internal static string RBI0002Description {
            get {
                return ResourceManager.GetString("RBI0002Description", resourceCulture);
            }
        }
        
        internal static string RBI0002MessageFormat {
            get {
                return ResourceManager.GetString("RBI0002MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0002Title {
            get {
                return ResourceManager.GetString("RBI0002Title", resourceCulture);
            }
        }
        
        internal static string RBI0003Description {
            get {
                return ResourceManager.GetString("RBI0003Description", resourceCulture);
            }
        }
        
        internal static string RBI0003MessageFormat {
            get {
                return ResourceManager.GetString("RBI0003MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0003Title {
            get {
                return ResourceManager.GetString("RBI0003Title", resourceCulture);
            }
        }
        
        internal static string RBI0004Description {
            get {
                return ResourceManager.GetString("RBI0004Description", resourceCulture);
            }
        }
        
        internal static string RBI0004MessageFormat {
            get {
                return ResourceManager.GetString("RBI0004MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0004Title {
            get {
                return ResourceManager.GetString("RBI0004Title", resourceCulture);
            }
        }
        
        internal static string RBI0005Description {
            get {
                return ResourceManager.GetString("RBI0005Description", resourceCulture);
            }
        }
        
        internal static string RBI0005MessageFormat {
            get {
                return ResourceManager.GetString("RBI0005MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0005Title {
            get {
                return ResourceManager.GetString("RBI0005Title", resourceCulture);
            }
        }
        
        internal static string RBI0006Description {
            get {
                return ResourceManager.GetString("RBI0006Description", resourceCulture);
            }
        }
        
        internal static string RBI0006MessageFormat {
            get {
                return ResourceManager.GetString("RBI0006MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0006Title {
            get {
                return ResourceManager.GetString("RBI0006Title", resourceCulture);
            }
        }
        
        internal static string RBI0007Description {
            get {
                return ResourceManager.GetString("RBI0007Description", resourceCulture);
            }
        }
        
        internal static string RBI0007MessageFormat {
            get {
                return ResourceManager.GetString("RBI0007MessageFormat", resourceCulture);
            }
        }
        
        internal static string RBI0007Title {
            get {
                return ResourceManager.GetString("RBI0007Title", resourceCulture);
            }
        }
    }
}
