#!/bin/sh
thisdir=`dirname $0`
thisdir=`cd $thisdir && pwd`
# MONO_GC_PARAMS="nursery-size=64m,$MONO_GC_PARAMS" exec /Library/Frameworks/Mono.framework/Versions/Current/bin/mono $MONO_OPTIONS $thisdir/MSBuild.dll "$@"

MSBUILD_EXE_PATH=$thisdir/MSBuild.dll mono --debug /Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/MSBuild.dll "$@"

