
#if PREFIX == 1
	#define theUltimateAnswer object_theUltimateAnswer
	#define useZLib           object_useZLib
	#define ObjCRegistrarTest object_ObjCRegistrarTest
	#define ObjCBlockTester   object_ObjCBlockTester
	#define FakeType2         object_FakeType2
	#define UltimateMachine   object_UltimateMachine
	#define FrameworkTest     object_FrameworkTest
	#define Sc                object_Sc
	#define Scc               object_Scc
	#define Sccc              object_Sccc
	#define Sd                object_Sd
	#define Sdd               object_Sdd
	#define Sddd              object_Sddd
	#define Sdddd             object_Sdddd
	#define Sddddd            object_Sddddd
	#define Si                object_Si
	#define Sii               object_Sii
	#define Siii              object_Siii
	#define Siiii             object_Siiii
	#define Siiiii            object_Siiiii
	#define Sid               object_Sid
	#define Sdi               object_Sdi
	#define Sidi              object_Sidi
	#define Sidid             object_Sidid
	#define Siid              object_Siid
	#define Sddi              object_Sddi
	#define Sdidi             object_Sdidi
	#define Sl                object_Sl
	#define Sll               object_Sll
	#define Slll              object_Slll
	#define Sllll             object_Sllll
	#define Slllll            object_Slllll
	#define Sldld             object_Sldld
	#define Sdldl             object_Sdldl
	#define Scccc             object_Scccc
	#define Sffff             object_Sffff
	#define Sif               object_Sif
	#define Sifif             object_Sifif
	#define Sf                object_Sf
	#define Sff               object_Sff
	#define Sfff              object_Sfff
	#define Sffff             object_Sffff
	#define Sfffff            object_Sfffff
	#define Siff              object_Siff
	#define Siiff             object_Siiff
	#define Sfi               object_Sfi
	#define Sfifi             object_Sfifi
	#define Ss                object_Ss
	#define Sss               object_Sss
	#define Ssss              object_Ssss
	#define Sssss             object_Sssss
	#define CtorChaining1     object_CtorChaining1
	#define ObjCExceptionTest object_ObjCExceptionTest
	#define ObjCProtocolClassTest object_ObjCProtocolClassTest
	#define x_mdltransform_get_rotation_matrix object_x_mdltransform_get_rotation_matrix
	#define x_mdltransformcomponent_get_local_transform object_x_mdltransformcomponent_get_local_transform
	#define x_mdltransform_create_global_transform object_x_mdltransform_create_global_transform
	#define x_get_matrix_float4x4 object_x_get_matrix_float4x4
	#define x_get_matrix_float4x3 object_x_get_matrix_float4x3
	#define x_get_matrix_float3x3 object_x_get_matrix_float3x3
	#define x_get_matrix_float2x2 object_x_get_matrix_float2x2
	#define x_call_block          object_x_call_block
#elif PREFIX == 2
	#define theUltimateAnswer ar_theUltimateAnswer
	#define useZLib           ar_useZLib
	#define ObjCRegistrarTest ar_ObjCRegistrarTest
	#define ObjCBlockTester   ar_ObjCBlockTester
	#define FakeType2         ar_FakeType2
	#define UltimateMachine   ar_UltimateMachine
	#define FrameworkTest     ar_FrameworkTest
	#define Sc                ar_Sc
	#define Scc               ar_Scc
	#define Sccc              ar_Sccc
	#define Sd                ar_Sd
	#define Sdd               ar_Sdd
	#define Sddd              ar_Sddd
	#define Sdddd             ar_Sdddd
	#define Sddddd            ar_Sddddd
	#define Si                ar_Si
	#define Sii               ar_Sii
	#define Siii              ar_Siii
	#define Siiii             ar_Siiii
	#define Siiiii            ar_Siiiii
	#define Sid               ar_Sid
	#define Sdi               ar_Sdi
	#define Sidi              ar_Sidi
	#define Sidid             ar_Sidid
	#define Siid              ar_Siid
	#define Sddi              ar_Sddi
	#define Sdidi             ar_Sdidi
	#define Sl                ar_Sl
	#define Sll               ar_Sll
	#define Slll              ar_Slll
	#define Sllll             ar_Sllll
	#define Slllll            ar_Slllll
	#define Sldld             ar_Sldld
	#define Sdldl             ar_Sdldl
	#define Scccc             ar_Scccc
	#define Sffff             ar_Sffff
	#define Sif               ar_Sif
	#define Sifif             ar_Sifif
	#define Sf                ar_Sf
	#define Sff               ar_Sff
	#define Sfff              ar_Sfff
	#define Sffff             ar_Sffff
	#define Sfffff            ar_Sfffff
	#define Siff              ar_Siff
	#define Siiff             ar_Siiff
	#define Sfi               ar_Sfi
	#define Sfifi             ar_Sfifi
	#define Ss                ar_Ss
	#define Sss               ar_Sss
	#define Ssss              ar_Ssss
	#define Sssss             ar_Sssss
	#define CtorChaining1     ar_CtorChaining1
	#define ObjCExceptionTest ar_ObjCExceptionTest
	#define ObjCProtocolClassTest ar_ObjCProtocolClassTest
	#define x_mdltransform_get_rotation_matrix ar_x_mdltransform_get_rotation_matrix
	#define x_mdltransformcomponent_get_local_transform ar_x_mdltransformcomponent_get_local_transform
	#define x_mdltransform_create_global_transform ar_x_mdltransform_create_global_transform
	#define x_get_matrix_float4x4 ar_x_get_matrix_float4x4
	#define x_get_matrix_float4x3 ar_x_get_matrix_float4x3
	#define x_get_matrix_float3x3 ar_x_get_matrix_float3x3
	#define x_get_matrix_float2x2 ar_x_get_matrix_float2x2
	#define x_call_block          ar_x_call_block
#else
// keep original names
#endif
