//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Localization.Mlaunch {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MLResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MLResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.Localization.Mlaunch.MLResources", typeof(MLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HE0001 {
            get {
                return ResourceManager.GetString("HE0001", resourceCulture);
            }
        }
        
        internal static string ML0002 {
            get {
                return ResourceManager.GetString("ML0002", resourceCulture);
            }
        }
        
        internal static string ML0002_A {
            get {
                return ResourceManager.GetString("ML0002_A", resourceCulture);
            }
        }
        
        internal static string HE0002_A {
            get {
                return ResourceManager.GetString("HE0002_A", resourceCulture);
            }
        }
        
        internal static string HE0003 {
            get {
                return ResourceManager.GetString("HE0003", resourceCulture);
            }
        }
        
        internal static string HE0003_A {
            get {
                return ResourceManager.GetString("HE0003_A", resourceCulture);
            }
        }
        
        internal static string HE0003_B {
            get {
                return ResourceManager.GetString("HE0003_B", resourceCulture);
            }
        }
        
        internal static string HE0004 {
            get {
                return ResourceManager.GetString("HE0004", resourceCulture);
            }
        }
        
        internal static string HE0005 {
            get {
                return ResourceManager.GetString("HE0005", resourceCulture);
            }
        }
        
        internal static string HE0005_A {
            get {
                return ResourceManager.GetString("HE0005_A", resourceCulture);
            }
        }
        
        internal static string ML0007 {
            get {
                return ResourceManager.GetString("ML0007", resourceCulture);
            }
        }
        
        internal static string HE0007 {
            get {
                return ResourceManager.GetString("HE0007", resourceCulture);
            }
        }
        
        internal static string HE0008 {
            get {
                return ResourceManager.GetString("HE0008", resourceCulture);
            }
        }
        
        internal static string HE0009 {
            get {
                return ResourceManager.GetString("HE0009", resourceCulture);
            }
        }
        
        internal static string ML0010 {
            get {
                return ResourceManager.GetString("ML0010", resourceCulture);
            }
        }
        
        internal static string ML0011 {
            get {
                return ResourceManager.GetString("ML0011", resourceCulture);
            }
        }
        
        internal static string ML0012 {
            get {
                return ResourceManager.GetString("ML0012", resourceCulture);
            }
        }
        
        internal static string HE0013 {
            get {
                return ResourceManager.GetString("HE0013", resourceCulture);
            }
        }
        
        internal static string ML0014 {
            get {
                return ResourceManager.GetString("ML0014", resourceCulture);
            }
        }
        
        internal static string ML0015 {
            get {
                return ResourceManager.GetString("ML0015", resourceCulture);
            }
        }
        
        internal static string ML0016 {
            get {
                return ResourceManager.GetString("ML0016", resourceCulture);
            }
        }
        
        internal static string ML0017 {
            get {
                return ResourceManager.GetString("ML0017", resourceCulture);
            }
        }
        
        internal static string ML0018 {
            get {
                return ResourceManager.GetString("ML0018", resourceCulture);
            }
        }
        
        internal static string HE0018 {
            get {
                return ResourceManager.GetString("HE0018", resourceCulture);
            }
        }
        
        internal static string HE0019 {
            get {
                return ResourceManager.GetString("HE0019", resourceCulture);
            }
        }
        
        internal static string ML0021 {
            get {
                return ResourceManager.GetString("ML0021", resourceCulture);
            }
        }
        
        internal static string ML0023 {
            get {
                return ResourceManager.GetString("ML0023", resourceCulture);
            }
        }
        
        internal static string ML0024 {
            get {
                return ResourceManager.GetString("ML0024", resourceCulture);
            }
        }
        
        internal static string ML0026 {
            get {
                return ResourceManager.GetString("ML0026", resourceCulture);
            }
        }
        
        internal static string ML0028 {
            get {
                return ResourceManager.GetString("ML0028", resourceCulture);
            }
        }
        
        internal static string ML0030 {
            get {
                return ResourceManager.GetString("ML0030", resourceCulture);
            }
        }
        
        internal static string ML0031 {
            get {
                return ResourceManager.GetString("ML0031", resourceCulture);
            }
        }
        
        internal static string ML0032 {
            get {
                return ResourceManager.GetString("ML0032", resourceCulture);
            }
        }
        
        internal static string ML0033 {
            get {
                return ResourceManager.GetString("ML0033", resourceCulture);
            }
        }
        
        internal static string ML0035 {
            get {
                return ResourceManager.GetString("ML0035", resourceCulture);
            }
        }
        
        internal static string ML0036 {
            get {
                return ResourceManager.GetString("ML0036", resourceCulture);
            }
        }
        
        internal static string ML0038 {
            get {
                return ResourceManager.GetString("ML0038", resourceCulture);
            }
        }
        
        internal static string ML0039 {
            get {
                return ResourceManager.GetString("ML0039", resourceCulture);
            }
        }
        
        internal static string ML0040 {
            get {
                return ResourceManager.GetString("ML0040", resourceCulture);
            }
        }
        
        internal static string ML0041 {
            get {
                return ResourceManager.GetString("ML0041", resourceCulture);
            }
        }
        
        internal static string ML0042 {
            get {
                return ResourceManager.GetString("ML0042", resourceCulture);
            }
        }
        
        internal static string ML0044 {
            get {
                return ResourceManager.GetString("ML0044", resourceCulture);
            }
        }
        
        internal static string ML0045 {
            get {
                return ResourceManager.GetString("ML0045", resourceCulture);
            }
        }
        
        internal static string ML0045_A {
            get {
                return ResourceManager.GetString("ML0045_A", resourceCulture);
            }
        }
        
        internal static string ML0045_B {
            get {
                return ResourceManager.GetString("ML0045_B", resourceCulture);
            }
        }
        
        internal static string ML0045_C {
            get {
                return ResourceManager.GetString("ML0045_C", resourceCulture);
            }
        }
        
        internal static string ML0045_D {
            get {
                return ResourceManager.GetString("ML0045_D", resourceCulture);
            }
        }
        
        internal static string ML0047 {
            get {
                return ResourceManager.GetString("ML0047", resourceCulture);
            }
        }
        
        internal static string ML0050 {
            get {
                return ResourceManager.GetString("ML0050", resourceCulture);
            }
        }
        
        internal static string ML0051 {
            get {
                return ResourceManager.GetString("ML0051", resourceCulture);
            }
        }
        
        internal static string ML0052 {
            get {
                return ResourceManager.GetString("ML0052", resourceCulture);
            }
        }
        
        internal static string ML0054 {
            get {
                return ResourceManager.GetString("ML0054", resourceCulture);
            }
        }
        
        internal static string ML0055 {
            get {
                return ResourceManager.GetString("ML0055", resourceCulture);
            }
        }
        
        internal static string ML0057 {
            get {
                return ResourceManager.GetString("ML0057", resourceCulture);
            }
        }
        
        internal static string ML0058 {
            get {
                return ResourceManager.GetString("ML0058", resourceCulture);
            }
        }
        
        internal static string ML0059 {
            get {
                return ResourceManager.GetString("ML0059", resourceCulture);
            }
        }
        
        internal static string ML0069 {
            get {
                return ResourceManager.GetString("ML0069", resourceCulture);
            }
        }
        
        internal static string ML0081 {
            get {
                return ResourceManager.GetString("ML0081", resourceCulture);
            }
        }
        
        internal static string ML0100 {
            get {
                return ResourceManager.GetString("ML0100", resourceCulture);
            }
        }
        
        internal static string ML0117 {
            get {
                return ResourceManager.GetString("ML0117", resourceCulture);
            }
        }
        
        internal static string ML1001 {
            get {
                return ResourceManager.GetString("ML1001", resourceCulture);
            }
        }
        
        internal static string ML1003 {
            get {
                return ResourceManager.GetString("ML1003", resourceCulture);
            }
        }
        
        internal static string ML1004 {
            get {
                return ResourceManager.GetString("ML1004", resourceCulture);
            }
        }
        
        internal static string ML1005 {
            get {
                return ResourceManager.GetString("ML1005", resourceCulture);
            }
        }
        
        internal static string ML1006 {
            get {
                return ResourceManager.GetString("ML1006", resourceCulture);
            }
        }
        
        internal static string ML1007 {
            get {
                return ResourceManager.GetString("ML1007", resourceCulture);
            }
        }
        
        internal static string ML1008 {
            get {
                return ResourceManager.GetString("ML1008", resourceCulture);
            }
        }
        
        internal static string ML1012 {
            get {
                return ResourceManager.GetString("ML1012", resourceCulture);
            }
        }
        
        internal static string ML1018 {
            get {
                return ResourceManager.GetString("ML1018", resourceCulture);
            }
        }
        
        internal static string ML1019 {
            get {
                return ResourceManager.GetString("ML1019", resourceCulture);
            }
        }
        
        internal static string ML1020 {
            get {
                return ResourceManager.GetString("ML1020", resourceCulture);
            }
        }
        
        internal static string ML1023 {
            get {
                return ResourceManager.GetString("ML1023", resourceCulture);
            }
        }
        
        internal static string ML1024 {
            get {
                return ResourceManager.GetString("ML1024", resourceCulture);
            }
        }
        
        internal static string ML1025 {
            get {
                return ResourceManager.GetString("ML1025", resourceCulture);
            }
        }
        
        internal static string ML1026 {
            get {
                return ResourceManager.GetString("ML1026", resourceCulture);
            }
        }
        
        internal static string ML1026_A {
            get {
                return ResourceManager.GetString("ML1026_A", resourceCulture);
            }
        }
        
        internal static string ML1027 {
            get {
                return ResourceManager.GetString("ML1027", resourceCulture);
            }
        }
        
        internal static string ML1028 {
            get {
                return ResourceManager.GetString("ML1028", resourceCulture);
            }
        }
        
        internal static string ML1029 {
            get {
                return ResourceManager.GetString("ML1029", resourceCulture);
            }
        }
        
        internal static string ML1030 {
            get {
                return ResourceManager.GetString("ML1030", resourceCulture);
            }
        }
        
        internal static string ML1031 {
            get {
                return ResourceManager.GetString("ML1031", resourceCulture);
            }
        }
        
        internal static string ML1031_A {
            get {
                return ResourceManager.GetString("ML1031_A", resourceCulture);
            }
        }
        
        internal static string ML1032 {
            get {
                return ResourceManager.GetString("ML1032", resourceCulture);
            }
        }
        
        internal static string ML1033 {
            get {
                return ResourceManager.GetString("ML1033", resourceCulture);
            }
        }
        
        internal static string ML1033_A {
            get {
                return ResourceManager.GetString("ML1033_A", resourceCulture);
            }
        }
        
        internal static string ML1034 {
            get {
                return ResourceManager.GetString("ML1034", resourceCulture);
            }
        }
        
        internal static string ML1043 {
            get {
                return ResourceManager.GetString("ML1043", resourceCulture);
            }
        }
        
        internal static string ML1101 {
            get {
                return ResourceManager.GetString("ML1101", resourceCulture);
            }
        }
        
        internal static string ML1102 {
            get {
                return ResourceManager.GetString("ML1102", resourceCulture);
            }
        }
        
        internal static string ML1103 {
            get {
                return ResourceManager.GetString("ML1103", resourceCulture);
            }
        }
        
        internal static string ML1104 {
            get {
                return ResourceManager.GetString("ML1104", resourceCulture);
            }
        }
        
        internal static string ML1105 {
            get {
                return ResourceManager.GetString("ML1105", resourceCulture);
            }
        }
        
        internal static string ML1106 {
            get {
                return ResourceManager.GetString("ML1106", resourceCulture);
            }
        }
        
        internal static string ML1107 {
            get {
                return ResourceManager.GetString("ML1107", resourceCulture);
            }
        }
        
        internal static string ML1109 {
            get {
                return ResourceManager.GetString("ML1109", resourceCulture);
            }
        }
        
        internal static string ML1111 {
            get {
                return ResourceManager.GetString("ML1111", resourceCulture);
            }
        }
        
        internal static string ML1202 {
            get {
                return ResourceManager.GetString("ML1202", resourceCulture);
            }
        }
        
        internal static string ML1203 {
            get {
                return ResourceManager.GetString("ML1203", resourceCulture);
            }
        }
        
        internal static string ML1203_A {
            get {
                return ResourceManager.GetString("ML1203_A", resourceCulture);
            }
        }
        
        internal static string ML1203_B {
            get {
                return ResourceManager.GetString("ML1203_B", resourceCulture);
            }
        }
        
        internal static string ML1204 {
            get {
                return ResourceManager.GetString("ML1204", resourceCulture);
            }
        }
        
        internal static string ML1205 {
            get {
                return ResourceManager.GetString("ML1205", resourceCulture);
            }
        }
        
        internal static string ML1206 {
            get {
                return ResourceManager.GetString("ML1206", resourceCulture);
            }
        }
        
        internal static string ML1207 {
            get {
                return ResourceManager.GetString("ML1207", resourceCulture);
            }
        }
        
        internal static string ML1210 {
            get {
                return ResourceManager.GetString("ML1210", resourceCulture);
            }
        }
        
        internal static string ML1211 {
            get {
                return ResourceManager.GetString("ML1211", resourceCulture);
            }
        }
        
        internal static string ML1212 {
            get {
                return ResourceManager.GetString("ML1212", resourceCulture);
            }
        }
        
        internal static string ML1216 {
            get {
                return ResourceManager.GetString("ML1216", resourceCulture);
            }
        }
        
        internal static string ML1220 {
            get {
                return ResourceManager.GetString("ML1220", resourceCulture);
            }
        }
        
        internal static string ML1221 {
            get {
                return ResourceManager.GetString("ML1221", resourceCulture);
            }
        }
        
        internal static string ML1400 {
            get {
                return ResourceManager.GetString("ML1400", resourceCulture);
            }
        }
        
        internal static string ML1401 {
            get {
                return ResourceManager.GetString("ML1401", resourceCulture);
            }
        }
        
        internal static string ML1402 {
            get {
                return ResourceManager.GetString("ML1402", resourceCulture);
            }
        }
        
        internal static string ML1403 {
            get {
                return ResourceManager.GetString("ML1403", resourceCulture);
            }
        }
        
        internal static string ML1403_A {
            get {
                return ResourceManager.GetString("ML1403_A", resourceCulture);
            }
        }
        
        internal static string ML1404 {
            get {
                return ResourceManager.GetString("ML1404", resourceCulture);
            }
        }
        
        internal static string ML1404_A {
            get {
                return ResourceManager.GetString("ML1404_A", resourceCulture);
            }
        }
        
        internal static string ML1405 {
            get {
                return ResourceManager.GetString("ML1405", resourceCulture);
            }
        }
        
        internal static string ML1406 {
            get {
                return ResourceManager.GetString("ML1406", resourceCulture);
            }
        }
        
        internal static string HE1800 {
            get {
                return ResourceManager.GetString("HE1800", resourceCulture);
            }
        }
        
        internal static string ML1801 {
            get {
                return ResourceManager.GetString("ML1801", resourceCulture);
            }
        }
        
        internal static string ML1802 {
            get {
                return ResourceManager.GetString("ML1802", resourceCulture);
            }
        }
        
        internal static string ML1803 {
            get {
                return ResourceManager.GetString("ML1803", resourceCulture);
            }
        }
        
        internal static string ML1804 {
            get {
                return ResourceManager.GetString("ML1804", resourceCulture);
            }
        }
        
        internal static string ML1805 {
            get {
                return ResourceManager.GetString("ML1805", resourceCulture);
            }
        }
        
        internal static string ML1900 {
            get {
                return ResourceManager.GetString("ML1900", resourceCulture);
            }
        }
        
        internal static string ML1901 {
            get {
                return ResourceManager.GetString("ML1901", resourceCulture);
            }
        }
        
        internal static string ML1902 {
            get {
                return ResourceManager.GetString("ML1902", resourceCulture);
            }
        }
        
        internal static string ML1903 {
            get {
                return ResourceManager.GetString("ML1903", resourceCulture);
            }
        }
    }
}
