//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.iOS.Tasks.Windows.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.iOS.Tasks.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Unzip_Error {
            get {
                return ResourceManager.GetString("Unzip_Error", resourceCulture);
            }
        }
        
        internal static string Unzip_Unzipped {
            get {
                return ResourceManager.GetString("Unzip_Unzipped", resourceCulture);
            }
        }
        
        internal static string Unzip_Unzipping {
            get {
                return ResourceManager.GetString("Unzip_Unzipping", resourceCulture);
            }
        }
        
        internal static string CollectDynamicFrameworks_InvalidFramework {
            get {
                return ResourceManager.GetString("CollectDynamicFrameworks_InvalidFramework", resourceCulture);
            }
        }
        
        internal static string Codesign_MissingPasswordFile {
            get {
                return ResourceManager.GetString("Codesign_MissingPasswordFile", resourceCulture);
            }
        }
        
        internal static string CompileAppManifest_MissinInfoPList {
            get {
                return ResourceManager.GetString("CompileAppManifest_MissinInfoPList", resourceCulture);
            }
        }
    }
}
