//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.iOS.Tasks.Windows.Properties {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.iOS.Tasks.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VerifyXcodeVersion_Error_WithDetails {
            get {
                return ResourceManager.GetString("VerifyXcodeVersion_Error_WithDetails", resourceCulture);
            }
        }
        
        internal static string VerifyXcodeVersion_Error {
            get {
                return ResourceManager.GetString("VerifyXcodeVersion_Error", resourceCulture);
            }
        }
        
        internal static string VerifyXcodeVersion_Mismatch {
            get {
                return ResourceManager.GetString("VerifyXcodeVersion_Mismatch", resourceCulture);
            }
        }
        
        internal static string ResolveUniversalTypeIdentifiers_Deserialize_Error {
            get {
                return ResourceManager.GetString("ResolveUniversalTypeIdentifiers_Deserialize_Error", resourceCulture);
            }
        }
        
        internal static string ResolveUniversalTypeIdentifiers_NoImageSet {
            get {
                return ResourceManager.GetString("ResolveUniversalTypeIdentifiers_NoImageSet", resourceCulture);
            }
        }
        
        internal static string ResolveUniversalTypeIdentifiers_UTI_Error {
            get {
                return ResourceManager.GetString("ResolveUniversalTypeIdentifiers_UTI_Error", resourceCulture);
            }
        }
        
        internal static string Task_NoConnectionAvailable {
            get {
                return ResourceManager.GetString("Task_NoConnectionAvailable", resourceCulture);
            }
        }
        
        internal static string ResolveUniversalTypeIdentifiers_GetUniversalTypeIdentifier {
            get {
                return ResourceManager.GetString("ResolveUniversalTypeIdentifiers_GetUniversalTypeIdentifier", resourceCulture);
            }
        }
        
        internal static string LocalUnzip_Error {
            get {
                return ResourceManager.GetString("LocalUnzip_Error", resourceCulture);
            }
        }
        
        internal static string LocalUnzip_Unzipped {
            get {
                return ResourceManager.GetString("LocalUnzip_Unzipped", resourceCulture);
            }
        }
        
        internal static string LocalUnzip_Unzipping {
            get {
                return ResourceManager.GetString("LocalUnzip_Unzipping", resourceCulture);
            }
        }
    }
}
