//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xamarin.Localization.MSBuild {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MSBStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MSBStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Xamarin.Localization.MSBuild.MSBStrings", typeof(MSBStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        public static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        public static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        public static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        public static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        public static string E0006 {
            get {
                return ResourceManager.GetString("E0006", resourceCulture);
            }
        }
        
        public static string E0007 {
            get {
                return ResourceManager.GetString("E0007", resourceCulture);
            }
        }
        
        public static string E0008 {
            get {
                return ResourceManager.GetString("E0008", resourceCulture);
            }
        }
        
        public static string E0009 {
            get {
                return ResourceManager.GetString("E0009", resourceCulture);
            }
        }
        
        public static string E0010 {
            get {
                return ResourceManager.GetString("E0010", resourceCulture);
            }
        }
        
        public static string E0011 {
            get {
                return ResourceManager.GetString("E0011", resourceCulture);
            }
        }
        
        public static string E0012 {
            get {
                return ResourceManager.GetString("E0012", resourceCulture);
            }
        }
        
        public static string E0013 {
            get {
                return ResourceManager.GetString("E0013", resourceCulture);
            }
        }
        
        public static string E0014 {
            get {
                return ResourceManager.GetString("E0014", resourceCulture);
            }
        }
        
        public static string E0015 {
            get {
                return ResourceManager.GetString("E0015", resourceCulture);
            }
        }
        
        public static string W0016 {
            get {
                return ResourceManager.GetString("W0016", resourceCulture);
            }
        }
        
        public static string M0017 {
            get {
                return ResourceManager.GetString("M0017", resourceCulture);
            }
        }
        
        public static string M0018 {
            get {
                return ResourceManager.GetString("M0018", resourceCulture);
            }
        }
        
        public static string W0019 {
            get {
                return ResourceManager.GetString("W0019", resourceCulture);
            }
        }
        
        public static string W0020 {
            get {
                return ResourceManager.GetString("W0020", resourceCulture);
            }
        }
        
        public static string W0021 {
            get {
                return ResourceManager.GetString("W0021", resourceCulture);
            }
        }
        
        public static string W0022 {
            get {
                return ResourceManager.GetString("W0022", resourceCulture);
            }
        }
        
        public static string E0023 {
            get {
                return ResourceManager.GetString("E0023", resourceCulture);
            }
        }
        
        public static string E0024 {
            get {
                return ResourceManager.GetString("E0024", resourceCulture);
            }
        }
        
        public static string E0025 {
            get {
                return ResourceManager.GetString("E0025", resourceCulture);
            }
        }
        
        public static string E0032 {
            get {
                return ResourceManager.GetString("E0032", resourceCulture);
            }
        }
        
        public static string E0044 {
            get {
                return ResourceManager.GetString("E0044", resourceCulture);
            }
        }
        
        public static string E0045 {
            get {
                return ResourceManager.GetString("E0045", resourceCulture);
            }
        }
        
        public static string E0046 {
            get {
                return ResourceManager.GetString("E0046", resourceCulture);
            }
        }
        
        public static string M0047 {
            get {
                return ResourceManager.GetString("M0047", resourceCulture);
            }
        }
        
        public static string E0048 {
            get {
                return ResourceManager.GetString("E0048", resourceCulture);
            }
        }
        
        public static string E0049 {
            get {
                return ResourceManager.GetString("E0049", resourceCulture);
            }
        }
        
        public static string E0050 {
            get {
                return ResourceManager.GetString("E0050", resourceCulture);
            }
        }
        
        public static string W0051 {
            get {
                return ResourceManager.GetString("W0051", resourceCulture);
            }
        }
        
        public static string W0052 {
            get {
                return ResourceManager.GetString("W0052", resourceCulture);
            }
        }
        
        public static string E0053 {
            get {
                return ResourceManager.GetString("E0053", resourceCulture);
            }
        }
        
        public static string W0054 {
            get {
                return ResourceManager.GetString("W0054", resourceCulture);
            }
        }
        
        public static string E0055 {
            get {
                return ResourceManager.GetString("E0055", resourceCulture);
            }
        }
        
        public static string E0056 {
            get {
                return ResourceManager.GetString("E0056", resourceCulture);
            }
        }
        
        public static string E0057 {
            get {
                return ResourceManager.GetString("E0057", resourceCulture);
            }
        }
        
        public static string E0058 {
            get {
                return ResourceManager.GetString("E0058", resourceCulture);
            }
        }
        
        public static string E0059 {
            get {
                return ResourceManager.GetString("E0059", resourceCulture);
            }
        }
        
        public static string E0060 {
            get {
                return ResourceManager.GetString("E0060", resourceCulture);
            }
        }
        
        public static string E0061 {
            get {
                return ResourceManager.GetString("E0061", resourceCulture);
            }
        }
        
        public static string E0062 {
            get {
                return ResourceManager.GetString("E0062", resourceCulture);
            }
        }
        
        public static string E0063 {
            get {
                return ResourceManager.GetString("E0063", resourceCulture);
            }
        }
        
        public static string E0064 {
            get {
                return ResourceManager.GetString("E0064", resourceCulture);
            }
        }
        
        public static string E0065 {
            get {
                return ResourceManager.GetString("E0065", resourceCulture);
            }
        }
        
        public static string E0066 {
            get {
                return ResourceManager.GetString("E0066", resourceCulture);
            }
        }
        
        public static string E0067 {
            get {
                return ResourceManager.GetString("E0067", resourceCulture);
            }
        }
        
        public static string E0068 {
            get {
                return ResourceManager.GetString("E0068", resourceCulture);
            }
        }
        
        public static string E0069 {
            get {
                return ResourceManager.GetString("E0069", resourceCulture);
            }
        }
        
        public static string E0070 {
            get {
                return ResourceManager.GetString("E0070", resourceCulture);
            }
        }
        
        public static string W0071 {
            get {
                return ResourceManager.GetString("W0071", resourceCulture);
            }
        }
        
        public static string W0072 {
            get {
                return ResourceManager.GetString("W0072", resourceCulture);
            }
        }
        
        public static string W0073 {
            get {
                return ResourceManager.GetString("W0073", resourceCulture);
            }
        }
        
        public static string W0074 {
            get {
                return ResourceManager.GetString("W0074", resourceCulture);
            }
        }
        
        public static string W0075 {
            get {
                return ResourceManager.GetString("W0075", resourceCulture);
            }
        }
        
        public static string W0076 {
            get {
                return ResourceManager.GetString("W0076", resourceCulture);
            }
        }
        
        public static string W0077 {
            get {
                return ResourceManager.GetString("W0077", resourceCulture);
            }
        }
        
        public static string W0078 {
            get {
                return ResourceManager.GetString("W0078", resourceCulture);
            }
        }
        
        public static string W0079 {
            get {
                return ResourceManager.GetString("W0079", resourceCulture);
            }
        }
        
        public static string W0080 {
            get {
                return ResourceManager.GetString("W0080", resourceCulture);
            }
        }
        
        public static string W0081 {
            get {
                return ResourceManager.GetString("W0081", resourceCulture);
            }
        }
        
        public static string W0082 {
            get {
                return ResourceManager.GetString("W0082", resourceCulture);
            }
        }
        
        public static string E0084 {
            get {
                return ResourceManager.GetString("E0084", resourceCulture);
            }
        }
        
        public static string E0085 {
            get {
                return ResourceManager.GetString("E0085", resourceCulture);
            }
        }
        
        public static string E0086 {
            get {
                return ResourceManager.GetString("E0086", resourceCulture);
            }
        }
        
        public static string E0088 {
            get {
                return ResourceManager.GetString("E0088", resourceCulture);
            }
        }
        
        public static string E0089 {
            get {
                return ResourceManager.GetString("E0089", resourceCulture);
            }
        }
        
        public static string W0090 {
            get {
                return ResourceManager.GetString("W0090", resourceCulture);
            }
        }
        
        public static string E0091 {
            get {
                return ResourceManager.GetString("E0091", resourceCulture);
            }
        }
        
        public static string E0092 {
            get {
                return ResourceManager.GetString("E0092", resourceCulture);
            }
        }
        
        public static string E0093 {
            get {
                return ResourceManager.GetString("E0093", resourceCulture);
            }
        }
        
        public static string E0094 {
            get {
                return ResourceManager.GetString("E0094", resourceCulture);
            }
        }
        
        public static string W0095 {
            get {
                return ResourceManager.GetString("W0095", resourceCulture);
            }
        }
        
        public static string E0097 {
            get {
                return ResourceManager.GetString("E0097", resourceCulture);
            }
        }
        
        public static string E0098 {
            get {
                return ResourceManager.GetString("E0098", resourceCulture);
            }
        }
        
        public static string E0099 {
            get {
                return ResourceManager.GetString("E0099", resourceCulture);
            }
        }
        
        public static string E0100 {
            get {
                return ResourceManager.GetString("E0100", resourceCulture);
            }
        }
        
        public static string E0101 {
            get {
                return ResourceManager.GetString("E0101", resourceCulture);
            }
        }
        
        public static string E0102 {
            get {
                return ResourceManager.GetString("E0102", resourceCulture);
            }
        }
        
        public static string W0103 {
            get {
                return ResourceManager.GetString("W0103", resourceCulture);
            }
        }
        
        public static string W0104 {
            get {
                return ResourceManager.GetString("W0104", resourceCulture);
            }
        }
        
        public static string M0105 {
            get {
                return ResourceManager.GetString("M0105", resourceCulture);
            }
        }
        
        public static string W0106 {
            get {
                return ResourceManager.GetString("W0106", resourceCulture);
            }
        }
        
        public static string E0107 {
            get {
                return ResourceManager.GetString("E0107", resourceCulture);
            }
        }
        
        public static string W0108 {
            get {
                return ResourceManager.GetString("W0108", resourceCulture);
            }
        }
        
        public static string W0109 {
            get {
                return ResourceManager.GetString("W0109", resourceCulture);
            }
        }
        
        public static string W0110 {
            get {
                return ResourceManager.GetString("W0110", resourceCulture);
            }
        }
        
        public static string W0111 {
            get {
                return ResourceManager.GetString("W0111", resourceCulture);
            }
        }
        
        public static string E0112 {
            get {
                return ResourceManager.GetString("E0112", resourceCulture);
            }
        }
        
        public static string E0113 {
            get {
                return ResourceManager.GetString("E0113", resourceCulture);
            }
        }
        
        public static string E0114 {
            get {
                return ResourceManager.GetString("E0114", resourceCulture);
            }
        }
        
        public static string E0115 {
            get {
                return ResourceManager.GetString("E0115", resourceCulture);
            }
        }
        
        public static string M0116 {
            get {
                return ResourceManager.GetString("M0116", resourceCulture);
            }
        }
        
        public static string E0117 {
            get {
                return ResourceManager.GetString("E0117", resourceCulture);
            }
        }
        
        public static string M0119 {
            get {
                return ResourceManager.GetString("M0119", resourceCulture);
            }
        }
        
        public static string E0120 {
            get {
                return ResourceManager.GetString("E0120", resourceCulture);
            }
        }
        
        public static string M0121 {
            get {
                return ResourceManager.GetString("M0121", resourceCulture);
            }
        }
        
        public static string E0122 {
            get {
                return ResourceManager.GetString("E0122", resourceCulture);
            }
        }
        
        public static string E0123 {
            get {
                return ResourceManager.GetString("E0123", resourceCulture);
            }
        }
        
        public static string E0124 {
            get {
                return ResourceManager.GetString("E0124", resourceCulture);
            }
        }
        
        public static string M0125 {
            get {
                return ResourceManager.GetString("M0125", resourceCulture);
            }
        }
        
        public static string M0126 {
            get {
                return ResourceManager.GetString("M0126", resourceCulture);
            }
        }
        
        public static string M0127 {
            get {
                return ResourceManager.GetString("M0127", resourceCulture);
            }
        }
        
        public static string E0128 {
            get {
                return ResourceManager.GetString("E0128", resourceCulture);
            }
        }
        
        public static string M0129 {
            get {
                return ResourceManager.GetString("M0129", resourceCulture);
            }
        }
        
        public static string E0130 {
            get {
                return ResourceManager.GetString("E0130", resourceCulture);
            }
        }
        
        public static string E0131 {
            get {
                return ResourceManager.GetString("E0131", resourceCulture);
            }
        }
        
        public static string M0132 {
            get {
                return ResourceManager.GetString("M0132", resourceCulture);
            }
        }
        
        public static string E0133 {
            get {
                return ResourceManager.GetString("E0133", resourceCulture);
            }
        }
        
        public static string M0134 {
            get {
                return ResourceManager.GetString("M0134", resourceCulture);
            }
        }
        
        public static string M0135 {
            get {
                return ResourceManager.GetString("M0135", resourceCulture);
            }
        }
        
        public static string M0136 {
            get {
                return ResourceManager.GetString("M0136", resourceCulture);
            }
        }
        
        public static string W0137 {
            get {
                return ResourceManager.GetString("W0137", resourceCulture);
            }
        }
        
        public static string M0138 {
            get {
                return ResourceManager.GetString("M0138", resourceCulture);
            }
        }
        
        public static string E0139 {
            get {
                return ResourceManager.GetString("E0139", resourceCulture);
            }
        }
        
        public static string E0140 {
            get {
                return ResourceManager.GetString("E0140", resourceCulture);
            }
        }
        
        public static string E0141 {
            get {
                return ResourceManager.GetString("E0141", resourceCulture);
            }
        }
        
        public static string M0142 {
            get {
                return ResourceManager.GetString("M0142", resourceCulture);
            }
        }
        
        public static string M0143 {
            get {
                return ResourceManager.GetString("M0143", resourceCulture);
            }
        }
        
        public static string E0144 {
            get {
                return ResourceManager.GetString("E0144", resourceCulture);
            }
        }
        
        public static string E0145 {
            get {
                return ResourceManager.GetString("E0145", resourceCulture);
            }
        }
        
        public static string E0146 {
            get {
                return ResourceManager.GetString("E0146", resourceCulture);
            }
        }
        
        public static string E0147 {
            get {
                return ResourceManager.GetString("E0147", resourceCulture);
            }
        }
        
        public static string E0148 {
            get {
                return ResourceManager.GetString("E0148", resourceCulture);
            }
        }
        
        public static string M0149 {
            get {
                return ResourceManager.GetString("M0149", resourceCulture);
            }
        }
        
        public static string E0150 {
            get {
                return ResourceManager.GetString("E0150", resourceCulture);
            }
        }
        
        public static string M0151 {
            get {
                return ResourceManager.GetString("M0151", resourceCulture);
            }
        }
        
        public static string E0152 {
            get {
                return ResourceManager.GetString("E0152", resourceCulture);
            }
        }
        
        public static string E0153 {
            get {
                return ResourceManager.GetString("E0153", resourceCulture);
            }
        }
        
        public static string E0154 {
            get {
                return ResourceManager.GetString("E0154", resourceCulture);
            }
        }
        
        public static string E0155 {
            get {
                return ResourceManager.GetString("E0155", resourceCulture);
            }
        }
        
        public static string E0156 {
            get {
                return ResourceManager.GetString("E0156", resourceCulture);
            }
        }
        
        public static string E0157 {
            get {
                return ResourceManager.GetString("E0157", resourceCulture);
            }
        }
        
        public static string E0158 {
            get {
                return ResourceManager.GetString("E0158", resourceCulture);
            }
        }
        
        public static string E0159 {
            get {
                return ResourceManager.GetString("E0159", resourceCulture);
            }
        }
        
        public static string E0160 {
            get {
                return ResourceManager.GetString("E0160", resourceCulture);
            }
        }
        
        public static string E0161 {
            get {
                return ResourceManager.GetString("E0161", resourceCulture);
            }
        }
        
        public static string M0162 {
            get {
                return ResourceManager.GetString("M0162", resourceCulture);
            }
        }
        
        public static string M0163 {
            get {
                return ResourceManager.GetString("M0163", resourceCulture);
            }
        }
        
        public static string M0164 {
            get {
                return ResourceManager.GetString("M0164", resourceCulture);
            }
        }
        
        public static string M0165 {
            get {
                return ResourceManager.GetString("M0165", resourceCulture);
            }
        }
        
        public static string E0166 {
            get {
                return ResourceManager.GetString("E0166", resourceCulture);
            }
        }
        
        public static string E0167 {
            get {
                return ResourceManager.GetString("E0167", resourceCulture);
            }
        }
        
        public static string M0168 {
            get {
                return ResourceManager.GetString("M0168", resourceCulture);
            }
        }
        
        public static string E0169 {
            get {
                return ResourceManager.GetString("E0169", resourceCulture);
            }
        }
        
        public static string E0170 {
            get {
                return ResourceManager.GetString("E0170", resourceCulture);
            }
        }
        
        public static string E0171 {
            get {
                return ResourceManager.GetString("E0171", resourceCulture);
            }
        }
        
        public static string E0172 {
            get {
                return ResourceManager.GetString("E0172", resourceCulture);
            }
        }
        
        public static string E0173 {
            get {
                return ResourceManager.GetString("E0173", resourceCulture);
            }
        }
        
        public static string E7001 {
            get {
                return ResourceManager.GetString("E7001", resourceCulture);
            }
        }
        
        public static string E7002 {
            get {
                return ResourceManager.GetString("E7002", resourceCulture);
            }
        }
        
        public static string E7003 {
            get {
                return ResourceManager.GetString("E7003", resourceCulture);
            }
        }
        
        public static string E7004 {
            get {
                return ResourceManager.GetString("E7004", resourceCulture);
            }
        }
        
        public static string E7005 {
            get {
                return ResourceManager.GetString("E7005", resourceCulture);
            }
        }
        
        public static string E7006 {
            get {
                return ResourceManager.GetString("E7006", resourceCulture);
            }
        }
        
        public static string E7007 {
            get {
                return ResourceManager.GetString("E7007", resourceCulture);
            }
        }
        
        public static string E7008 {
            get {
                return ResourceManager.GetString("E7008", resourceCulture);
            }
        }
        
        public static string E7009 {
            get {
                return ResourceManager.GetString("E7009", resourceCulture);
            }
        }
        
        public static string E7010 {
            get {
                return ResourceManager.GetString("E7010", resourceCulture);
            }
        }
        
        public static string E7011 {
            get {
                return ResourceManager.GetString("E7011", resourceCulture);
            }
        }
        
        public static string E7012 {
            get {
                return ResourceManager.GetString("E7012", resourceCulture);
            }
        }
        
        public static string E7012_A {
            get {
                return ResourceManager.GetString("E7012_A", resourceCulture);
            }
        }
        
        public static string E7013 {
            get {
                return ResourceManager.GetString("E7013", resourceCulture);
            }
        }
        
        public static string E7013_A {
            get {
                return ResourceManager.GetString("E7013_A", resourceCulture);
            }
        }
        
        public static string E7013_B {
            get {
                return ResourceManager.GetString("E7013_B", resourceCulture);
            }
        }
        
        public static string E7014 {
            get {
                return ResourceManager.GetString("E7014", resourceCulture);
            }
        }
        
        public static string E7015 {
            get {
                return ResourceManager.GetString("E7015", resourceCulture);
            }
        }
        
        public static string E7016 {
            get {
                return ResourceManager.GetString("E7016", resourceCulture);
            }
        }
        
        public static string E7017 {
            get {
                return ResourceManager.GetString("E7017", resourceCulture);
            }
        }
        
        public static string E7018 {
            get {
                return ResourceManager.GetString("E7018", resourceCulture);
            }
        }
        
        public static string E7019 {
            get {
                return ResourceManager.GetString("E7019", resourceCulture);
            }
        }
        
        public static string E7020 {
            get {
                return ResourceManager.GetString("E7020", resourceCulture);
            }
        }
        
        public static string E7021 {
            get {
                return ResourceManager.GetString("E7021", resourceCulture);
            }
        }
        
        public static string E7022 {
            get {
                return ResourceManager.GetString("E7022", resourceCulture);
            }
        }
        
        public static string E7022_A {
            get {
                return ResourceManager.GetString("E7022_A", resourceCulture);
            }
        }
        
        public static string E7023 {
            get {
                return ResourceManager.GetString("E7023", resourceCulture);
            }
        }
        
        public static string E7024 {
            get {
                return ResourceManager.GetString("E7024", resourceCulture);
            }
        }
        
        public static string E7025 {
            get {
                return ResourceManager.GetString("E7025", resourceCulture);
            }
        }
        
        public static string E7026 {
            get {
                return ResourceManager.GetString("E7026", resourceCulture);
            }
        }
        
        public static string E7027 {
            get {
                return ResourceManager.GetString("E7027", resourceCulture);
            }
        }
        
        public static string E7028 {
            get {
                return ResourceManager.GetString("E7028", resourceCulture);
            }
        }
        
        public static string E7029 {
            get {
                return ResourceManager.GetString("E7029", resourceCulture);
            }
        }
        
        public static string E7029_A {
            get {
                return ResourceManager.GetString("E7029_A", resourceCulture);
            }
        }
        
        public static string E7030 {
            get {
                return ResourceManager.GetString("E7030", resourceCulture);
            }
        }
        
        public static string E7031 {
            get {
                return ResourceManager.GetString("E7031", resourceCulture);
            }
        }
        
        public static string E7031_A {
            get {
                return ResourceManager.GetString("E7031_A", resourceCulture);
            }
        }
        
        public static string E7032 {
            get {
                return ResourceManager.GetString("E7032", resourceCulture);
            }
        }
        
        public static string E7032_A {
            get {
                return ResourceManager.GetString("E7032_A", resourceCulture);
            }
        }
        
        public static string E7033 {
            get {
                return ResourceManager.GetString("E7033", resourceCulture);
            }
        }
        
        public static string E7034 {
            get {
                return ResourceManager.GetString("E7034", resourceCulture);
            }
        }
        
        public static string E7035 {
            get {
                return ResourceManager.GetString("E7035", resourceCulture);
            }
        }
        
        public static string E7036 {
            get {
                return ResourceManager.GetString("E7036", resourceCulture);
            }
        }
        
        public static string E7037 {
            get {
                return ResourceManager.GetString("E7037", resourceCulture);
            }
        }
        
        public static string E7038 {
            get {
                return ResourceManager.GetString("E7038", resourceCulture);
            }
        }
        
        public static string E7038_A {
            get {
                return ResourceManager.GetString("E7038_A", resourceCulture);
            }
        }
        
        public static string E7039 {
            get {
                return ResourceManager.GetString("E7039", resourceCulture);
            }
        }
        
        public static string E7040 {
            get {
                return ResourceManager.GetString("E7040", resourceCulture);
            }
        }
        
        public static string E7041 {
            get {
                return ResourceManager.GetString("E7041", resourceCulture);
            }
        }
        
        public static string E7042 {
            get {
                return ResourceManager.GetString("E7042", resourceCulture);
            }
        }
        
        public static string E7043 {
            get {
                return ResourceManager.GetString("E7043", resourceCulture);
            }
        }
        
        public static string E7044 {
            get {
                return ResourceManager.GetString("E7044", resourceCulture);
            }
        }
        
        public static string E7044_A {
            get {
                return ResourceManager.GetString("E7044_A", resourceCulture);
            }
        }
        
        public static string E7045 {
            get {
                return ResourceManager.GetString("E7045", resourceCulture);
            }
        }
        
        public static string E7046 {
            get {
                return ResourceManager.GetString("E7046", resourceCulture);
            }
        }
        
        public static string E7047 {
            get {
                return ResourceManager.GetString("E7047", resourceCulture);
            }
        }
        
        public static string E7048 {
            get {
                return ResourceManager.GetString("E7048", resourceCulture);
            }
        }
        
        public static string E7049 {
            get {
                return ResourceManager.GetString("E7049", resourceCulture);
            }
        }
        
        public static string E7050 {
            get {
                return ResourceManager.GetString("E7050", resourceCulture);
            }
        }
        
        public static string E7051 {
            get {
                return ResourceManager.GetString("E7051", resourceCulture);
            }
        }
        
        public static string E7052 {
            get {
                return ResourceManager.GetString("E7052", resourceCulture);
            }
        }
        
        public static string E7053 {
            get {
                return ResourceManager.GetString("E7053", resourceCulture);
            }
        }
        
        public static string E7054 {
            get {
                return ResourceManager.GetString("E7054", resourceCulture);
            }
        }
        
        public static string E7055 {
            get {
                return ResourceManager.GetString("E7055", resourceCulture);
            }
        }
        
        public static string E7056 {
            get {
                return ResourceManager.GetString("E7056", resourceCulture);
            }
        }
        
        public static string E7057 {
            get {
                return ResourceManager.GetString("E7057", resourceCulture);
            }
        }
        
        public static string E7058 {
            get {
                return ResourceManager.GetString("E7058", resourceCulture);
            }
        }
        
        public static string E7059 {
            get {
                return ResourceManager.GetString("E7059", resourceCulture);
            }
        }
        
        public static string E7060 {
            get {
                return ResourceManager.GetString("E7060", resourceCulture);
            }
        }
        
        public static string E7061 {
            get {
                return ResourceManager.GetString("E7061", resourceCulture);
            }
        }
        
        public static string E7062 {
            get {
                return ResourceManager.GetString("E7062", resourceCulture);
            }
        }
        
        public static string E7063 {
            get {
                return ResourceManager.GetString("E7063", resourceCulture);
            }
        }
        
        public static string E7064 {
            get {
                return ResourceManager.GetString("E7064", resourceCulture);
            }
        }
        
        public static string E7068 {
            get {
                return ResourceManager.GetString("E7068", resourceCulture);
            }
        }
    }
}
