# These tests were removed in 76900f9f104302058f2bad6eed81089972909ee2 but we can't
# keep wrench from calling due to C5 right now. Just stub to empty
run run-test run-tests:
	@/usr/bin/true
clean:
	@/usr/bin/true
