using System.Linq;
using Xamarin.Tests;
using Xamarin.Utils;
using Xunit;

namespace Microsoft.Macios.Generator.Tests;

// Unit test that ensures that all the generator attributes are correctly added in the compilation initialization
public class BindingSourceGeneratorGeneratorTests : BaseGeneratorTestClass {

	const string usingImportInput = @"
using System;
using Foundation;
using ObjCBindings;
namespace TestNamespace;

[BindingType (Name = ""AVAudioPCMBuffer"")]
public partial class AVAudioPcmBuffer : AVAudioBuffer {
}
";

	const string usingImportOutput = @"// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using System;

namespace TestNamespace
{
	public partial class AVAudioPcmBuffer
	{
		// TODO: add binding code here
	}
}
";

	[Theory]
	[AllSupportedPlatforms (usingImportInput, usingImportOutput)]
	public void CorrectUsingImports (ApplePlatform platform, string input, string expectedOutput)
	{
		// We need to create a compilation with the required source code.
		var (compilation, _) = CreateCompilation (nameof (CorrectUsingImports),
			platform, input);

		// Run generators and retrieve all results.
		var runResult = Driver.RunGenerators (compilation).GetRunResult ();
		Assert.Empty (runResult.Diagnostics);

		// ensure that we do have all the needed attributes present
		var generatedFile = runResult.GeneratedTrees.SingleOrDefault (t => t.FilePath.EndsWith ("AVAudioPcmBuffer.g.cs"));
		Assert.NotNull (generatedFile);
		Assert.Equal (expectedOutput, generatedFile.GetText ().ToString ());
	}
}
