$(IOS_BUILD_DIR)/compat/OpenTK.dll.config: ./OpenGLES/OpenTK/OpenTK.dll.config | $(IOS_BUILD_DIR)/compat
	$(Q) cp $< $@

$(IOS_BUILD_DIR)/compat/OpenTK.dll: Makefile OpenGLES/Makefile.include $(shell cat OpenTK.dll.sources) $(IOS_BUILD_DIR)/compat/monotouch.dll | $(IOS_BUILD_DIR)/compat
	$(Q_MCS) $(IOS_CSC) -warn:0 -unsafe -target:library -debug+ -define:MONOTOUCH -define:IPHONE -d:MINIMAL -out:$@ @./$(@F).sources -r:$(IOS_BUILD_DIR)/compat/monotouch.dll -keyfile:$(PRODUCT_KEY_PATH)
	$(Q) touch $@

$(IOS_BUILD_DIR)/compat/OpenTK.dll.mdb: $(IOS_BUILD_DIR)/compat/OpenTK.dll
	@touch $@
