#!/usr/bin/env bash

selfdir=$( cd "$(dirname "$0")" ; pwd -P )
pmcsdir=$( cd "$selfdir/../lib/pmcs"; pwd -P )
pmcs="$pmcsdir/pmcs.exe"

echo "PMCS: Internal Xamarin Tool. Do not use."

case $1 in
	--profile | -profile)
		profile="$2"
		shift 2
		;;
	--profile=*)
		profile="${1:10}"
		shift
		;;
	--profile:*)
		profile="${1:10}"
		shift
		;;
	-profile=*)
		profile="${1:9}"
		shift
		;;
	-profile:*)
		profile="${1:9}"
		shift
		;;
esac

if test -z "$profile"; then
	if test -z "$PMCS_PROFILE"; then
		echo "pmcs: no profile (--profile=[classic|unified|full/path/to/custom/profile]) specified" 1>&2
		exit 1
	fi
	profile="$PMCS_PROFILE"
fi

if test -f "$profile"; then
	echo nothing to do > /dev/null
elif test -f "$pmcsdir/profiles/$profile"; then
	profile="$pmcsdir/profiles/$profile"
else
	echo "pmcs: invalid profile: '$profile'" 1>&2
	exit 1
fi

mono --debug "$pmcs" \
	-profile:"$profile" \
	-compiler:/Library/Frameworks/Mono.framework/Versions/Current/bin/mcs \
	"$@"
