#!/usr/bin/env bash

self="$(dirname "$0")"
build_in_place_dir="$(python -c "import os; print os.path.realpath('$self/../_mac-build')")"
xammac_framework_dir="$build_in_place_dir/Library/Frameworks/Xamarin.Mac.framework/Versions/Current"
xbuild_external_dir="$build_in_place_dir/Library/Frameworks/Mono.framework/External"

export TargetFrameworkFallbackSearchPaths="$xbuild_external_dir/xbuild-frameworks"
export MSBuildExtensionsPathFallbackPathsOverride="$xbuild_external_dir/xbuild"

XamarinMacFrameworkRoot="$xammac_framework_dir"
TargetFrameworkIdentifier=Xamarin.Mac
TargetFrameworkVersion=v2.0

$(self)/../tools/xibuild/bin/Debug/xibuild.exe -- \
	/property:XamarinMacFrameworkRoot="$XamarinMacFrameworkRoot" \
	/property:TargetFrameworkIdentifier="$TargetFrameworkIdentifier" \
	/property:TargetFrameworkVersion="$TargetFrameworkVersion" \
	"$@"
