#!/bin/bash -e

ABSOLUTE_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")
TOOL_DIR=$(dirname "$ABSOLUTE_PATH")

if ! test -f "$TOOL_DIR"/bin/Debug/*/xibuild; then
	make -C "$TOOL_DIR"
fi

exec "$TOOL_DIR"/bin/Debug/*/xibuild "$@"
