// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.ComponentModel;
using System.IO;

namespace Microsoft.Macios.Generator.IO;

static class TabbedStringBuilderExtensions {
	/// <summary>
	/// Append the generated code attribute to the current string builder. Added for convenience.
	/// </summary>
	/// <param name="self">A tabbed string builder.</param>
	/// <param name="optimizable">If the binding is Optimizable or not.</param>
	/// <returns>The current builder.</returns>
	public static TabbedWriter<StringWriter> AppendGeneratedCodeAttribute (this TabbedWriter<StringWriter> self, bool optimizable = true)
	{
		if (optimizable) {
			const string attr = "[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]";
			self.WriteLine (attr);
		} else {
			const string attr = "[BindingImpl (BindingImplOptions.GeneratedCode)]";
			self.WriteLine (attr);
		}

		return self;
	}

	/// <summary>
	/// Append the notification advice attribute to the current string builder. Added for convenience.
	/// </summary>
	/// <param name="self">A tabbed string builder.</param>
	/// <param name="className">The class that contains the notification.</param>
	/// <param name="notification">The name of the notification.</param>
	/// <returns></returns>
	public static TabbedWriter<StringWriter> AppendNotificationAdvice (this TabbedWriter<StringWriter> self, in string className, in string notification)
	{
		string attr =
			$"[Advice (\"Use '{className}.Notifications.{notification}' helper method instead.\")]";
		self.WriteLine (attr);
		return self;
	}

	/// <summary>
	/// Append a EditorBrowsable attribute. Added for convenience.
	/// </summary>
	/// <param name="self">A tabbed string builder.</param>
	/// <returns>The current builder.</returns>
	public static TabbedWriter<StringWriter> AppendEditorBrowsableAttribute (this TabbedWriter<StringWriter> self, EditorBrowsableState state)
	{
		string attr = $"[EditorBrowsable (EditorBrowsableState.{state})]";
		self.WriteLine (attr);
		return self;
	}

	/// <summary>
	/// Append the designated initializer attribute to the current string builder. Added for convenience. 
	/// </summary>
	/// <param name="self">A tabbed string builder.</param>
	/// <returns>The current builder.</returns>
	public static TabbedWriter<StringWriter> AppendDesignatedInitializer (this TabbedWriter<StringWriter> self)
	{
		const string attr = "[DesignatedInitializer]";
		self.WriteLine (attr);
		return self;
	}

	/// <summary>
	/// Writes the autogenerated header and other pragmas.
	/// </summary>
	/// <param name="self">A tabbed string builder.</param>
	/// <returns>The current builder.</returns>
	public static TabbedWriter<StringWriter> WriteHeader (this TabbedWriter<StringWriter> self)
	{
		// let people know this is generated code
		self.WriteLine ("// <auto-generated />");

		// enable nullable!
		self.WriteLine ();
		self.WriteLine ("#nullable enable");
		self.WriteLine ();
		return self;
	}
}
