//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nnyeah {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nnyeah.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string E0001 {
            get {
                return ResourceManager.GetString("E0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file &apos;{0}&apos; already exists. Use &apos;--force-overwrite&apos; if you want to overwrite it..
        /// </summary>
        internal static string E0002 {
            get {
                return ResourceManager.GetString("E0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read module from file {0}: {1}..
        /// </summary>
        internal static string E0003 {
            get {
                return ResourceManager.GetString("E0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate output file, unexpected exception: {0}..
        /// </summary>
        internal static string E0004 {
            get {
                return ResourceManager.GetString("E0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module is not loaded. Call Load first..
        /// </summary>
        internal static string E0005 {
            get {
                return ResourceManager.GetString("E0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IConvertible interfaces are not supported yet. If this code gets called, it will fail. Consider contacting the library maintainer to request a dotnet 6 upgrade..
        /// </summary>
        internal static string N0001 {
            get {
                return ResourceManager.GetString("N0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyArray for nuint is not supported yet. If this method is called, it will not function correctly..
        /// </summary>
        internal static string N0002 {
            get {
                return ResourceManager.GetString("N0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package does not need changes - no output generated..
        /// </summary>
        internal static string N0003 {
            get {
                return ResourceManager.GetString("N0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0}.{1}, found reference to {2}. Added {3} IL instructions and removed {4} IL instructions..
        /// </summary>
        internal static string N0004 {
            get {
                return ResourceManager.GetString("N0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0}.{1}, found reference to {2}. Added {3} IL instructions..
        /// </summary>
        internal static string N0005 {
            get {
                return ResourceManager.GetString("N0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0}.{1}, found reference to {2} - this is not transformable and will likely not work if invoked..
        /// </summary>
        internal static string N0006 {
            get {
                return ResourceManager.GetString("N0006", resourceCulture);
            }
        }
    }
}
