// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace ObjCRuntime;

[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
static partial class Libraries
{
	static public class __Internal
	{
		static public readonly IntPtr Handle = Dlfcn.dlopen (null, 0);
	}
}
