// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace MySingleView
{
	public partial class CustomViewController : UIViewController
	{
		public CustomViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
