//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mtouch {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("mtouch.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MT0000 {
            get {
                return ResourceManager.GetString("MT0000", resourceCulture);
            }
        }
        
        internal static string MT0001 {
            get {
                return ResourceManager.GetString("MT0001", resourceCulture);
            }
        }
        
        internal static string MT0002 {
            get {
                return ResourceManager.GetString("MT0002", resourceCulture);
            }
        }
        
        internal static string MT0003 {
            get {
                return ResourceManager.GetString("MT0003", resourceCulture);
            }
        }
        
        internal static string MT0004 {
            get {
                return ResourceManager.GetString("MT0004", resourceCulture);
            }
        }
        
        internal static string MT0005 {
            get {
                return ResourceManager.GetString("MT0005", resourceCulture);
            }
        }
        
        internal static string MT0006 {
            get {
                return ResourceManager.GetString("MT0006", resourceCulture);
            }
        }
        
        internal static string MT0007 {
            get {
                return ResourceManager.GetString("MT0007", resourceCulture);
            }
        }
        
        internal static string MT0008 {
            get {
                return ResourceManager.GetString("MT0008", resourceCulture);
            }
        }
        
        internal static string MT0009 {
            get {
                return ResourceManager.GetString("MT0009", resourceCulture);
            }
        }
        
        internal static string MT0010 {
            get {
                return ResourceManager.GetString("MT0010", resourceCulture);
            }
        }
        
        internal static string MT0011 {
            get {
                return ResourceManager.GetString("MT0011", resourceCulture);
            }
        }
        
        internal static string MT0012 {
            get {
                return ResourceManager.GetString("MT0012", resourceCulture);
            }
        }
        
        internal static string MT0013 {
            get {
                return ResourceManager.GetString("MT0013", resourceCulture);
            }
        }
        
        internal static string MT0014 {
            get {
                return ResourceManager.GetString("MT0014", resourceCulture);
            }
        }
        
        internal static string MT0015 {
            get {
                return ResourceManager.GetString("MT0015", resourceCulture);
            }
        }
        
        internal static string MT0016 {
            get {
                return ResourceManager.GetString("MT0016", resourceCulture);
            }
        }
        
        internal static string MT0017 {
            get {
                return ResourceManager.GetString("MT0017", resourceCulture);
            }
        }
        
        internal static string MT0018 {
            get {
                return ResourceManager.GetString("MT0018", resourceCulture);
            }
        }
        
        internal static string MT0019 {
            get {
                return ResourceManager.GetString("MT0019", resourceCulture);
            }
        }
        
        internal static string MT0020 {
            get {
                return ResourceManager.GetString("MT0020", resourceCulture);
            }
        }
        
        internal static string MT0021 {
            get {
                return ResourceManager.GetString("MT0021", resourceCulture);
            }
        }
        
        internal static string MT0022 {
            get {
                return ResourceManager.GetString("MT0022", resourceCulture);
            }
        }
        
        internal static string MT0023 {
            get {
                return ResourceManager.GetString("MT0023", resourceCulture);
            }
        }
        
        internal static string MT0024 {
            get {
                return ResourceManager.GetString("MT0024", resourceCulture);
            }
        }
        
        internal static string MT0025 {
            get {
                return ResourceManager.GetString("MT0025", resourceCulture);
            }
        }
        
        internal static string MT0026 {
            get {
                return ResourceManager.GetString("MT0026", resourceCulture);
            }
        }
        
        internal static string MT0027 {
            get {
                return ResourceManager.GetString("MT0027", resourceCulture);
            }
        }
        
        internal static string MT0028 {
            get {
                return ResourceManager.GetString("MT0028", resourceCulture);
            }
        }
        
        internal static string MT0029 {
            get {
                return ResourceManager.GetString("MT0029", resourceCulture);
            }
        }
        
        internal static string MT0030 {
            get {
                return ResourceManager.GetString("MT0030", resourceCulture);
            }
        }
        
        internal static string MT0031 {
            get {
                return ResourceManager.GetString("MT0031", resourceCulture);
            }
        }
        
        internal static string MT0032 {
            get {
                return ResourceManager.GetString("MT0032", resourceCulture);
            }
        }
        
        internal static string MT0033 {
            get {
                return ResourceManager.GetString("MT0033", resourceCulture);
            }
        }
        
        internal static string MT0034 {
            get {
                return ResourceManager.GetString("MT0034", resourceCulture);
            }
        }
        
        internal static string MT0036 {
            get {
                return ResourceManager.GetString("MT0036", resourceCulture);
            }
        }
        
        internal static string MT0037 {
            get {
                return ResourceManager.GetString("MT0037", resourceCulture);
            }
        }
        
        internal static string MT0038 {
            get {
                return ResourceManager.GetString("MT0038", resourceCulture);
            }
        }
        
        internal static string MT0039 {
            get {
                return ResourceManager.GetString("MT0039", resourceCulture);
            }
        }
        
        internal static string MT0040 {
            get {
                return ResourceManager.GetString("MT0040", resourceCulture);
            }
        }
        
        internal static string MT0041 {
            get {
                return ResourceManager.GetString("MT0041", resourceCulture);
            }
        }
        
        internal static string MT0042 {
            get {
                return ResourceManager.GetString("MT0042", resourceCulture);
            }
        }
        
        internal static string MT0043 {
            get {
                return ResourceManager.GetString("MT0043", resourceCulture);
            }
        }
        
        internal static string MT0044 {
            get {
                return ResourceManager.GetString("MT0044", resourceCulture);
            }
        }
        
        internal static string MT0045 {
            get {
                return ResourceManager.GetString("MT0045", resourceCulture);
            }
        }
        
        internal static string MT0047 {
            get {
                return ResourceManager.GetString("MT0047", resourceCulture);
            }
        }
        
        internal static string MT0049 {
            get {
                return ResourceManager.GetString("MT0049", resourceCulture);
            }
        }
        
        internal static string MT0051 {
            get {
                return ResourceManager.GetString("MT0051", resourceCulture);
            }
        }
        
        internal static string MT0052 {
            get {
                return ResourceManager.GetString("MT0052", resourceCulture);
            }
        }
        
        internal static string MT0054 {
            get {
                return ResourceManager.GetString("MT0054", resourceCulture);
            }
        }
        
        internal static string MT0055 {
            get {
                return ResourceManager.GetString("MT0055", resourceCulture);
            }
        }
        
        internal static string MT0056 {
            get {
                return ResourceManager.GetString("MT0056", resourceCulture);
            }
        }
        
        internal static string MT0057 {
            get {
                return ResourceManager.GetString("MT0057", resourceCulture);
            }
        }
        
        internal static string MT0058 {
            get {
                return ResourceManager.GetString("MT0058", resourceCulture);
            }
        }
        
        internal static string MT0059 {
            get {
                return ResourceManager.GetString("MT0059", resourceCulture);
            }
        }
        
        internal static string MT0060 {
            get {
                return ResourceManager.GetString("MT0060", resourceCulture);
            }
        }
        
        internal static string MT0061 {
            get {
                return ResourceManager.GetString("MT0061", resourceCulture);
            }
        }
        
        internal static string MT0062 {
            get {
                return ResourceManager.GetString("MT0062", resourceCulture);
            }
        }
        
        internal static string MT0063 {
            get {
                return ResourceManager.GetString("MT0063", resourceCulture);
            }
        }
        
        internal static string MT0064 {
            get {
                return ResourceManager.GetString("MT0064", resourceCulture);
            }
        }
        
        internal static string MT0065 {
            get {
                return ResourceManager.GetString("MT0065", resourceCulture);
            }
        }
        
        internal static string MT0066 {
            get {
                return ResourceManager.GetString("MT0066", resourceCulture);
            }
        }
        
        internal static string MT0067 {
            get {
                return ResourceManager.GetString("MT0067", resourceCulture);
            }
        }
        
        internal static string MT0068 {
            get {
                return ResourceManager.GetString("MT0068", resourceCulture);
            }
        }
        
        internal static string MT0070 {
            get {
                return ResourceManager.GetString("MT0070", resourceCulture);
            }
        }
        
        internal static string MT0071 {
            get {
                return ResourceManager.GetString("MT0071", resourceCulture);
            }
        }
        
        internal static string MT0072 {
            get {
                return ResourceManager.GetString("MT0072", resourceCulture);
            }
        }
        
        internal static string MT0073 {
            get {
                return ResourceManager.GetString("MT0073", resourceCulture);
            }
        }
        
        internal static string MT0074 {
            get {
                return ResourceManager.GetString("MT0074", resourceCulture);
            }
        }
        
        internal static string MT0075 {
            get {
                return ResourceManager.GetString("MT0075", resourceCulture);
            }
        }
        
        internal static string MT0076 {
            get {
                return ResourceManager.GetString("MT0076", resourceCulture);
            }
        }
        
        internal static string MT0077 {
            get {
                return ResourceManager.GetString("MT0077", resourceCulture);
            }
        }
        
        internal static string MT0078 {
            get {
                return ResourceManager.GetString("MT0078", resourceCulture);
            }
        }
        
        internal static string MT0079 {
            get {
                return ResourceManager.GetString("MT0079", resourceCulture);
            }
        }
        
        internal static string MT0080 {
            get {
                return ResourceManager.GetString("MT0080", resourceCulture);
            }
        }
        
        internal static string MT0081 {
            get {
                return ResourceManager.GetString("MT0081", resourceCulture);
            }
        }
        
        internal static string MT0082 {
            get {
                return ResourceManager.GetString("MT0082", resourceCulture);
            }
        }
        
        internal static string MT0083 {
            get {
                return ResourceManager.GetString("MT0083", resourceCulture);
            }
        }
        
        internal static string MT0084 {
            get {
                return ResourceManager.GetString("MT0084", resourceCulture);
            }
        }
        
        internal static string MT0085 {
            get {
                return ResourceManager.GetString("MT0085", resourceCulture);
            }
        }
        
        internal static string MT0086 {
            get {
                return ResourceManager.GetString("MT0086", resourceCulture);
            }
        }
        
        internal static string MT0087 {
            get {
                return ResourceManager.GetString("MT0087", resourceCulture);
            }
        }
        
        internal static string MT0088 {
            get {
                return ResourceManager.GetString("MT0088", resourceCulture);
            }
        }
        
        internal static string MT0089 {
            get {
                return ResourceManager.GetString("MT0089", resourceCulture);
            }
        }
        
        internal static string MT0091 {
            get {
                return ResourceManager.GetString("MT0091", resourceCulture);
            }
        }
        
        internal static string MT0093 {
            get {
                return ResourceManager.GetString("MT0093", resourceCulture);
            }
        }
        
        internal static string MT0095 {
            get {
                return ResourceManager.GetString("MT0095", resourceCulture);
            }
        }
        
        internal static string MT0096 {
            get {
                return ResourceManager.GetString("MT0096", resourceCulture);
            }
        }
        
        internal static string MT0099 {
            get {
                return ResourceManager.GetString("MT0099", resourceCulture);
            }
        }
        
        internal static string MT0100 {
            get {
                return ResourceManager.GetString("MT0100", resourceCulture);
            }
        }
        
        internal static string MT0101 {
            get {
                return ResourceManager.GetString("MT0101", resourceCulture);
            }
        }
        
        internal static string MT0102 {
            get {
                return ResourceManager.GetString("MT0102", resourceCulture);
            }
        }
        
        internal static string MT0103 {
            get {
                return ResourceManager.GetString("MT0103", resourceCulture);
            }
        }
        
        internal static string MT0105 {
            get {
                return ResourceManager.GetString("MT0105", resourceCulture);
            }
        }
        
        internal static string MT0106 {
            get {
                return ResourceManager.GetString("MT0106", resourceCulture);
            }
        }
        
        internal static string MT0107 {
            get {
                return ResourceManager.GetString("MT0107", resourceCulture);
            }
        }
        
        internal static string MT0108 {
            get {
                return ResourceManager.GetString("MT0108", resourceCulture);
            }
        }
        
        internal static string MT0109 {
            get {
                return ResourceManager.GetString("MT0109", resourceCulture);
            }
        }
        
        internal static string MT0110 {
            get {
                return ResourceManager.GetString("MT0110", resourceCulture);
            }
        }
        
        internal static string MT0111 {
            get {
                return ResourceManager.GetString("MT0111", resourceCulture);
            }
        }
        
        internal static string MT0112 {
            get {
                return ResourceManager.GetString("MT0112", resourceCulture);
            }
        }
        
        internal static string MT0113 {
            get {
                return ResourceManager.GetString("MT0113", resourceCulture);
            }
        }
        
        internal static string MT0115 {
            get {
                return ResourceManager.GetString("MT0115", resourceCulture);
            }
        }
        
        internal static string MT0116 {
            get {
                return ResourceManager.GetString("MT0116", resourceCulture);
            }
        }
        
        internal static string MT0117 {
            get {
                return ResourceManager.GetString("MT0117", resourceCulture);
            }
        }
        
        internal static string MT0118 {
            get {
                return ResourceManager.GetString("MT0118", resourceCulture);
            }
        }
        
        internal static string MT0123 {
            get {
                return ResourceManager.GetString("MT0123", resourceCulture);
            }
        }
        
        internal static string MT0124 {
            get {
                return ResourceManager.GetString("MT0124", resourceCulture);
            }
        }
        
        internal static string MT0125 {
            get {
                return ResourceManager.GetString("MT0125", resourceCulture);
            }
        }
        
        internal static string MT0126 {
            get {
                return ResourceManager.GetString("MT0126", resourceCulture);
            }
        }
        
        internal static string MT0127 {
            get {
                return ResourceManager.GetString("MT0127", resourceCulture);
            }
        }
        
        internal static string MT0128 {
            get {
                return ResourceManager.GetString("MT0128", resourceCulture);
            }
        }
        
        internal static string MT0129 {
            get {
                return ResourceManager.GetString("MT0129", resourceCulture);
            }
        }
        
        internal static string MT0130 {
            get {
                return ResourceManager.GetString("MT0130", resourceCulture);
            }
        }
        
        internal static string MT0131 {
            get {
                return ResourceManager.GetString("MT0131", resourceCulture);
            }
        }
        
        internal static string MT0132 {
            get {
                return ResourceManager.GetString("MT0132", resourceCulture);
            }
        }
        
        internal static string MT0133 {
            get {
                return ResourceManager.GetString("MT0133", resourceCulture);
            }
        }
        
        internal static string MT0135 {
            get {
                return ResourceManager.GetString("MT0135", resourceCulture);
            }
        }
        
        internal static string MT0136 {
            get {
                return ResourceManager.GetString("MT0136", resourceCulture);
            }
        }
        
        internal static string MT0137 {
            get {
                return ResourceManager.GetString("MT0137", resourceCulture);
            }
        }
        
        internal static string MT0140 {
            get {
                return ResourceManager.GetString("MT0140", resourceCulture);
            }
        }
    }
}
