//
// BackgroundAssets C# bindings
//
// Authors:
//	Manuel de la Pena Saenz <mandel@microsoft.com>
//
// Copyright 2022 Microsoft Corporation All rights reserved.
//

using System;

using CoreFoundation;
using Foundation;
using ObjCRuntime;

#if !NET
using NativeHandle = System.IntPtr;
#endif

namespace BackgroundAssets {
	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
	[Native]
	public enum BADownloadState : long {
		Failed = -1,
		Created = 0,
		Waiting,
		Downloading,
		Finished,
	}

	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	interface BADownload : NSCoding, NSSecureCoding, NSCopying
	{
		[Export ("state")]
		BADownloadState State { get; }

		[Export ("identifier")]
		string Identifier { get; }

		[Export ("uniqueIdentifier")]
		string UniqueIdentifier { get; }

		[Export ("priority")]
		nint Priority { get; }

		[NullAllowed, Export ("error")]
		NSError Error { get; }
	}

	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
	[BaseType (typeof (NSObject))]
	interface BAApplicationExtensionInfo : NSSecureCoding
	{
		[Export ("applicationIdentifier")]
		string ApplicationIdentifier { get; }

		[NullAllowed, Export ("lastPeriodicCheckTime")]
		NSDate LastPeriodicCheckTime { get; }

		[NullAllowed, Export ("lastApplicationLaunchTime")]
		NSDate LastApplicationLaunchTime { get; }

		[Export ("downloadSizeRestricted")]
		bool DownloadSizeRestricted { get; }
	}

	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
	[Protocol]
	interface BADownloaderExtension {

		[Export ("applicationDidInstallWithMetadata:")]
		void DidInstallWithMetadata (BAApplicationExtensionInfo metadata);

		[Export ("applicationDidUpdateWithMetadata:")]
		void DidUpdateWithMetadata (BAApplicationExtensionInfo metadata);

		[Export ("checkForUpdatesWithMetadata:")]
		void CheckForUpdates (BAApplicationExtensionInfo metadata);

		[Export ("receivedAuthenticationChallenge:download:completionHandler:")]
		void ReceivedAuthenticationChallenge (NSUrlAuthenticationChallenge challenge, BADownload download, Action<NSUrlSessionAuthChallengeDisposition, NSUrlCredential> completionHandler);

		[Export ("backgroundDownloadDidFail:")]
		void BackgroundDownloadDidFail (BADownload failedDownload);

		[Export ("backgroundDownloadDidFinish:fileURL:")]
		void BackgroundDownloadDidFinish (BADownload finishedDownload, NSUrl fileUrl);

		[Export ("extensionWillTerminate")]
		void ExtensionWillTerminate ();
	}

	interface IBADownloadManagerDelegate {}

	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
#if NET
	[Protocol][Model]
#else
	[Protocol][Model (AutoGeneratedName = true)]
#endif
	[BaseType (typeof (NSObject))]
	interface BADownloadManagerDelegate
	{
		[Export ("downloadDidBegin:")]
		void DidBegin (BADownload download);

		[Export ("downloadDidPause:")]
		void DidPause (BADownload download);

		[Export ("download:didWriteBytes:totalBytesWritten:totalBytesExpectedToWrite:")]
		void DidWriteBytes (BADownload download, long bytesWritten, long totalBytesWritten, long totalExpectedBytes);

		[Export ("download:didReceiveChallenge:completionHandler:")]
		void DidReceiveChallenge (BADownload download, NSUrlAuthenticationChallenge challenge, Action<NSUrlSessionAuthChallengeDisposition, NSUrlCredential> completionHandler);

		[Export ("download:failedWithError:")]
		void failed (BADownload download, NSError error);

		[Export ("download:finishedWithFileURL:")]
		void finished (BADownload download, NSUrl fileUrl);
	}

	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	interface BADownloadManager
	{
		[Static]
		[Export ("sharedManager", ArgumentSemantic.Strong)]
		BADownloadManager SharedManager { get; }

		[Wrap ("WeakDelegate")]
		[NullAllowed]
		IBADownloadManagerDelegate Delegate { get; set; }

		[NullAllowed, Export ("delegate", ArgumentSemantic.Weak)]
		NSObject WeakDelegate { get; set; }

		[Async]
		[Export ("fetchCurrentDownloadsWithCompletionHandler:")]
		void FetchCurrentDownloads (Action<NSArray<BADownload>, NSError> completionHandler);

		[Export ("scheduleDownload:error:")]
		bool ScheduleDownload (BADownload download, [NullAllowed] out NSError outError);

		[Export ("performWithExclusiveControl:")]
		void PerformWithExclusiveControl (Action<NSError> performHandler);

		[Export ("performWithExclusiveControlBeforeDate:completion:")]
		void PerformWithExclusiveControl (NSDate date, Action<bool, NSError> performHandler);

		[Export ("startForegroundDownload:error:")]
		bool StartForegroundDownload (BADownload download, [NullAllowed] out NSError outError);

		[Export ("cancelDownload:error:")]
		bool CancelDownload (BADownload download, [NullAllowed] out NSError error);
	}

	[NoWatch, NoTV, Mac (13,0), iOS (16,0), MacCatalyst (16,0)]
	[BaseType (typeof (BADownload))]
	[DisableDefaultCtor]
	interface BAURLDownload
	{

		[Field ("BADownloaderPriorityMin")]
		nint MinPriority { get; }

		[Field ("BADownloaderPriorityDefault")]
		nint DefaultPriority { get; }

		[Field ("BADownloaderPriorityMax")]
		nint MaxPriority { get; }

		[Export ("initWithIdentifier:request:applicationGroupIdentifier:")]
		NativeHandle Constructor (string identifier, NSUrlRequest request, string applicationGroupIdentifier);

		[Export ("initWithIdentifier:request:applicationGroupIdentifier:priority:")]
		[DesignatedInitializer]
		NativeHandle Constructor (string identifier, NSUrlRequest request, string applicationGroupIdentifier, nint priority);
	}

}
