//
// IncomingCallNotifications C# bindings
//
// Authors:
//	TJ Lambert  <t-anlamb@microsoft.com>
//
// Copyright 2019 Microsoft Corporation
// All rights reserved.
//

using System;
using CoreFoundation;
using Foundation;
using ObjCRuntime;

namespace IncomingCallNotifications {

	[iOS (13,0)]
	[Native]
	enum ICHandleType : long {
		Generic = 1,
		PhoneNumber = 2,
		EmailAddress = 3,
	}

	[iOS (13,0)]
	[Native]
	enum ICDeclineReason : long {
		Generic,
		Cancelled,
		UserBusy,
		Unanswered,
	}

	[iOS (13,0)]
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	interface ICHandle : INSCopying {

		[Export ("type")]
		ICHandleType Type { get; }

		[Export ("value", ArgumentSemantic.Copy)]
		string Value { get; }

		[DesignatedInitializer]
		[Export ("initWithType:value:")]
		IntPtr Constructor (ICHandleType type, string value);

		[Export ("isEqualToHandle:")]
		bool IsEqual (ICHandle handle);

		// // required from NSCopying
		// [Export ("copyWithZone:")]
		// NSObject Copy (NSZone zone);
	}

	[iOS (13,0)]
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	interface ICNotification : INSCopying {

		[DesignatedInitializer]
		[Export ("initWithUUID:handle:")]
		IntPtr Constructor (NSUuid identifier, ICHandle handle);

		[Export ("identifier", ArgumentSemantic.Copy)]
		NSUuid Identifier { get; }

		[Export ("handle", ArgumentSemantic.Copy)]
		ICHandle PersonHandle { get; }

		[Export ("video", ArgumentSemantic.Assign)]
		bool Video { [Bind ("isVideo")] get; set; }

		// // required from NSCopying
		// [Export ("copyWithZone:")]
		// NSObject Copy (NSZone zone);
	}

	[iOS (13,0)]
	[BaseType (typeof (NSObject))]
	[Model (AutoGeneratedName = true)] [Protocol]
	interface ICNotificationManagerDelegate {

		[Export ("notificationManager:didAcceptNotification:")]
		void DidAcceptNotification (ICNotificationManager notificationManager, ICNotification notification);

		[Export ("notificationManager:didDeclineNotification:reason:")]
		void DidDeclineNotification (ICNotificationManager notificationManager, ICNotification notification, ICDeclineReason reason);
	}

	interface IICNotificationManagerDelegate {}

	[iOS (13,0)]
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	interface ICNotificationManager {

		[DesignatedInitializer]
		[Export ("initWithConfiguration:")]
		IntPtr Constructor (ICNotificationManagerConfiguration configuration);

		[Export ("setDelegate:queue:")]
		void SetDelegate ([NullAllowed] IICNotificationManagerDelegate WeakDelegate, [NullAllowed] DispatchQueue queue);

		[Export ("postNotification:completion:")]
		void PostNotification (ICNotification notification, [NullAllowed] Action<NSError> completion);

		[Export ("cancelNotificationWithIdentifier:")]
		void PostNotification (NSUuid identifier);
	}

	[iOS (13,0)]
	[BaseType (typeof (NSObject))]
	interface ICNotificationManagerConfiguration : INSCopying {

		[Export ("localizedDisplayName", ArgumentSemantic.Copy), NullAllowed]
		string DisplayName { get; set; }

		// // required from NSCopying
		// [Export ("copyWithZone:")]
		// NSObject Copy (NSZone zone);
	}
}

